(() => {
'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const kinds={town:'TOWN EDITOR',route:'ROUTE EDITOR',dungeon:'LANDMARK EDITOR',special:'AREA EDITOR'};
const roles=['outdoors','homes','shops','pokemon_centers','gyms','story','dungeon','floors','other'];
const roleNames={outdoors:'Outdoor maps',homes:'Homes',shops:'Shops',pokemon_centers:'Pokémon Centers',gyms:'Gyms',story:'Story buildings & activities',dungeon:'Caves & underground',floors:'Rooms & floors',other:'Other maps'};
let catalog, selected, kind='town', token, creating='town', pending=false;
document.querySelectorAll('[data-kind],#new-town,#new-route').forEach(b=>b.disabled=true);
async function api(url,body){const res=await fetch(url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Token':token},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw Error(data.error||'Could not update this area.');return data;}
const world=n=>'/worldmap?map='+encodeURIComponent(n), connect=n=>'/connections?map='+encodeURIComponent(n), story=n=>'/campaign?map='+encodeURIComponent(n), preview=n=>'/api/world/maps/'+encodeURIComponent(n)+'/preview.png';
function renderList(){if(!catalog)return;document.querySelectorAll('[data-kind],#new-town,#new-route').forEach(b=>b.disabled=false);const q=$('#search').value.toLowerCase().replace(/\s+/g,'');const areas=catalog.areas.filter(a=>(q||kind==='all'||a.kind===kind)&&(!q||(a.name+a.id+a.maps.map(m=>m.name+m.display_name).join('')).toLowerCase().replace(/\s+/g,'').includes(q)));$('#count').textContent=areas.length+' AREAS · '+areas.reduce((n,a)=>n+a.count,0)+' MAPS';$('#areas').replaceChildren();for(const a of areas){const b=document.createElement('button');b.className='area-row'+(selected?.id===a.id?' active':'');b.setAttribute('aria-label',a.name);b.innerHTML=`<span>${esc(a.name)}<small>${a.kind==='route'?'Route':a.kind==='town'?'Town / city':a.kind==='dungeon'?'Cave / landmark':'Special area'}</small></span><span class="area-size">${a.count}</span>`;b.onclick=()=>select(a);$('#areas').append(b);}if(!areas.length)$('#areas').innerHTML='<p class="empty">No matching areas.</p>';document.querySelectorAll('[data-kind]').forEach(b=>b.classList.toggle('active',b.dataset.kind===kind));}
function card(m){return `<article class="map-card"><a class="map-picture" href="${world(m.name)}" aria-label="Edit ${esc(m.display_name||m.name)}"><img loading="lazy" src="${preview(m.name)}" alt="${esc(m.display_name||m.name)} layout"></a><div class="map-card-copy"><h4>${esc(m.display_name||m.name)}</h4><p>${m.width} × ${m.height} tiles · ${m.event_counts?.objects||0} people / objects</p><div class="map-card-actions"><a href="${world(m.name)}">Edit map →</a><a href="${connect(m.name)}">Doors & links</a><a href="${story(m.name)}">Story</a></div></div></article>`;}
function select(area){selected=area;history.replaceState(null,'','/areas?area='+encodeURIComponent(area.id));document.title=area.name+' · '+(kinds[area.kind]||'Area editor');renderList();const base=area.maps.find(m=>m.name===area.exterior)||area.maps[0];const label=area.kind==='town'?'town':area.kind==='route'?'route':'area';$('#area-heading').innerHTML=`<div><p class="eyebrow">${kinds[area.kind]||'AREA EDITOR'}</p><h2>${esc(area.name)}</h2><p class="muted">${area.count} map${area.count===1?'':'s'} organized in one workspace.</p></div><div class="area-actions"><a class="button primary" href="${world(base.name)}">Edit entire ${label} →</a><button id="add-interior">＋ Add interior</button><a class="button" href="${connect(base.name)}">Connect places</a></div>`;$('#add-interior').onclick=()=>openCreate('interior');const c={objects:0,warps:0,triggers:0,interactions:0};area.maps.forEach(m=>Object.keys(c).forEach(k=>c[k]+=m.event_counts?.[k]||0));let html=`<div class="overview"><article class="outdoor"><a class="image-stage" href="${world(base.name)}" aria-label="Edit whole ${esc(area.name)}"><img src="${preview(base.name)}" alt="Whole ${esc(area.name)} map"></a><div class="outdoor-caption"><div><h3>${area.exterior?'The whole landscape':'Main map'}</h3><p>${base.width} × ${base.height} tiles · Paint, resize, add buildings and place objects.</p></div><a class="button primary" href="${world(base.name)}">Open editor</a></div></article><div class="workspaces"><a class="workspace-card" href="${connect(base.name)}"><strong>⇄ Roads, doors & stairs</strong><p>Choose where this area leads. Link neighboring routes and both ends of every entrance.</p></a><a class="workspace-card" href="${story(base.name)}"><strong>☷ People & story</strong><p>Write this area's dialogue, events and progression. Each building below has its own Story link.</p></a><a class="workspace-card" href="${world(base.name)}"><strong>▧ Land, buildings & objects</strong><p>Work on the complete landscape. Houses and shops have separate interior maps, grouped below.</p></a>${area.kind==='town'?'<a class="workspace-card" href="/campaign?tab=trainers"><strong>♙ Trainers & gym battles</strong><p>Choose teams, levels, portraits and battle settings. Gym maps and their story are below.</p></a>':'<a class="workspace-card" href="/?path=src%2Fdata%2Fwild_encounters.json#files"><strong>◉ Wild encounters</strong><p>Open the encounter source table to choose which Pokémon appear. Species definitions stay unchanged.</p></a>'}</div></div><div class="counts"><span><b>${area.count}</b> maps</span><span><b>${c.objects}</b> people / objects</span><span><b>${c.warps}</b> entrances</span><span><b>${c.triggers+c.interactions}</b> triggers / interactions</span></div>`;
for(const role of roles){const maps=area.maps.filter(m=>m.role===role);if(!maps.length)continue;html+=`<section><div class="group-heading"><h3>${esc(maps[0].role_label||roleNames[role])}</h3><span>${maps.length} map${maps.length===1?'':'s'}</span></div><div class="map-grid">${maps.map(card).join('')}</div></section>`;}
const unknown=area.maps.filter(m=>!roles.includes(m.role));if(unknown.length)html+='<section><div class="group-heading"><h3>Other maps</h3></div><div class="map-grid">'+unknown.map(card).join('')+'</div></section>';$('#area-content').innerHTML=html;}
function openCreate(type){creating=type;$('#create-error').hidden=true;$('#create-form').reset();$('#create-title').textContent=type==='interior'?'Add an interior to '+selected.name:type==='route'?'Build a new route':'Build a new town';$('#create-description').textContent=type==='interior'?'The new map will be grouped inside this area. After painting it, use Connect places to give it an entrance.':'Create the full outdoor map first. Add houses, shops, caves and other interiors from its area workspace.';$('#template-label').hidden=type!=='interior';$('#new-name').value=type==='interior'?selected.id+'_House1':'';$('#new-name').placeholder=type==='route'?'MyNewRoute':'MyNewTown';$('#name-help').textContent=type==='interior'?'Keep the '+selected.id+'_ prefix to keep this map in the area.':'Use a unique name beginning with a capital letter, without spaces.';$('#width').value=type==='route'?20:type==='interior'?12:30;$('#height').value=type==='route'?60:type==='interior'?12:30;$('#create-dialog').showModal();}
$('#create-form').onsubmit=async e=>{e.preventDefault();if(pending)return;const name=$('#new-name').value.trim(),width=Number($('#width').value),height=Number($('#height').value);try{if(creating==='interior'&&!name.startsWith(selected.id+'_'))throw Error('Keep the '+selected.id+'_ prefix for this area.');if((width+15)*(height+14)>10240)throw Error('This map is too large. Use smaller dimensions.');pending=true;$('#create-submit').disabled=true;const template=creating==='town'?'LittlerootTown':creating==='route'?'Route101':$('#template').value;await api('/api/world/new',{name,template,width,height,blank:true});location.href='/worldmap?map='+encodeURIComponent(name);}catch(err){$('#create-error').textContent=err.message;$('#create-error').hidden=false;}finally{pending=false;$('#create-submit').disabled=false;}};
for(const id of ['cancel','close-dialog'])$('#'+id).onclick=()=>{if(!pending)$('#create-dialog').close();};$('#create-dialog').addEventListener('cancel',e=>{if(pending)e.preventDefault();});$('#new-town').onclick=()=>openCreate('town');$('#new-route').onclick=()=>openCreate('route');$('#search').oninput=()=>renderList();document.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.kind;$('#search').value='';renderList();const first=catalog.areas.find(a=>kind==='all'||a.kind===kind);if(first&&selected.kind!==kind&&kind!=='all')select(first);});
(async()=>{try{const [session,areas]=await Promise.all([api('/api/session'),api('/api/areas')]);token=session.token;catalog=areas;const p=new URLSearchParams(location.search),requested=p.get('area'),map=p.get('map');const initial=catalog.areas.find(a=>a.id===requested||map&&a.maps.some(m=>m.name===map))||catalog.areas.find(a=>a.id==='LittlerootTown')||catalog.areas[0];kind=initial.kind;select(initial);}catch(err){$('#error').textContent=err.message;$('#error').hidden=false;}})();
})();
