(() => {
  'use strict';
  const $=(q,root=document)=>root.querySelector(q), $$=(q,root=document)=>[...root.querySelectorAll(q)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const nice=v=>String(v||'').replace(/^MAP_/, '').replace(/([a-z\d])([A-Z])/g,'$1 $2').replace(/_/g,' ').replace(/(\D)(\d)/g,'$1 $2');
  const directions={up:'North',right:'East',down:'South',left:'West'}, arrows={up:'↑',right:'→',down:'↓',left:'←',dive:'↓',emerge:'↑'};
  const opposite={up:'down',down:'up',left:'right',right:'left'};
  const S={token:'',catalog:null,maps:[],byName:new Map(),mode:'edges',filter:'all',a:'LittlerootTown',b:'Route101',direction:'up',offset:0,scale:6,
    nodes:new Map(),positions:new Map(),drag:null,busy:false,images:new Map(),imageVersion:0,door:{a:{map:'LittlerootTown',x:null,y:null,elevation:0,index:null},b:{map:'LittlerootTown_BrendansHouse_1F',x:null,y:null,elevation:0,index:null}},doorImages:{a:null,b:null},doorZoom:{a:1,b:1},doorRequests:{a:0,b:0},dialogResolve:null,toastTimer:null};
  const ORIGIN=400,SPAN=1000,viewport=$('#board-viewport');
  function node(tag,cls='',text){const n=document.createElement(tag);n.className=cls;if(text!==undefined)n.textContent=text;return n;}
  async function api(url,body){const response=await fetch(url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Token':S.token},body:JSON.stringify(body)});let data;try{data=await response.json();}catch{throw new Error(`Could not read the server response (${response.status}).`);}if(!response.ok)throw new Error(typeof data.error==='string'?data.error:data.error?.message||data.message||`Request failed (${response.status}).`);return data;}
  function error(message=''){$('#error').textContent=message;$('#error').hidden=!message;}
  function toast(message,bad=false){clearTimeout(S.toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;$('#toast').classList.toggle('error',bad);S.toastTimer=setTimeout(()=>$('#toast').hidden=true,bad?8000:4300);}
  function current(name){return S.byName.get(name);}
  function preview(map){return `${map.preview_url||`/api/world/maps/${encodeURIComponent(map.name)}/preview.png`}?v=${S.imageVersion}`;}
  function imageFor(map){const key=preview(map);if(!S.images.has(key))S.images.set(key,new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error(`Artwork for ${nice(map.name)} could not be loaded.`));image.src=key;}));return S.images.get(key);}
  function status(){const count=S.catalog?.maps.length;$('#source-status').textContent=S.busy?'Saving…':count?`${count} locations`:'Loading…';$('#reload').disabled=S.busy;$('#add-map').disabled=S.busy;updateEdgeSummary();updateDoorSummary();}
  function dialog(title,html,button='Continue',info=false){if($('#dialog').open)return Promise.resolve(null);$('#dialog-title').textContent=title;$('#dialog-content').innerHTML=html;$('#dialog-submit').textContent=button;$('#dialog-submit').hidden=info;$('#dialog-cancel').textContent=info?'Got it':'Cancel';$('#dialog').showModal();return new Promise(resolve=>S.dialogResolve=resolve);}
  function closeDialog(value){$('#dialog').close();const resolve=S.dialogResolve;S.dialogResolve=null;if(resolve)resolve(value);}
  $('#dialog-form').onsubmit=e=>{e.preventDefault();closeDialog(Object.fromEntries(new FormData(e.currentTarget)));};$('#dialog-cancel').onclick=()=>closeDialog(null);$('#dialog-close').onclick=()=>closeDialog(null);$('#dialog').oncancel=e=>{e.preventDefault();closeDialog(null);};
  function populateSelect(select,selected){select.replaceChildren(...S.maps.map(map=>{const option=node('option','',nice(map.name));option.value=map.name;return option;}));select.value=current(selected)?selected:S.maps[0]?.name||'';}
  function catalogRows(){const query=$('#map-search').value.toLowerCase().replace(/\s/g,'');const maps=S.maps.filter(map=>(!query||`${map.name}${nice(map.name)}`.toLowerCase().replace(/\s/g,'').includes(query))&&(S.filter!=='outdoor'||['MAP_TYPE_TOWN','MAP_TYPE_CITY','MAP_TYPE_ROUTE'].includes(map.map_type)));$('#map-count').textContent=`${maps.length} locations`;const frag=document.createDocumentFragment();maps.forEach(map=>{const button=node('button',`map-row${map.name===(S.mode==='edges'?S.a:S.door.a.map)?' active':''}`);button.type='button';button.title=map.name;button.innerHTML=`<span class="map-icon">${map.map_type==='MAP_TYPE_ROUTE'?'⌁':/TOWN|CITY/.test(map.map_type)?'⌂':'▧'}</span><span><strong>${esc(nice(map.name))}</strong><small>${map.connections.length} paths · ${map.warps.length} doors</small></span>${map.warnings.length?'<span class="warning-mark" title="Some links need review">◇</span>':''}`;button.onclick=()=>{if(S.busy)return;if(S.mode==='edges')focusArea(map.name);else setDoorMap('a',map.name,true);};frag.append(button);});$('#map-list').replaceChildren(frag);if(!maps.length)$('#map-list').append(node('p','list-empty','No matching locations.'));}
  async function loadCatalog(initial=false){
    if(S.busy&&!initial)return;error('');
    try{const catalog=await api('/api/connections');S.catalog=catalog;S.maps=catalog.maps;S.byName=new Map(S.maps.map(map=>[map.name,map]));
      if(!current(S.a))S.a='LittlerootTown';if(!current(S.b))S.b=S.maps.find(map=>map.name!==S.a)?.name||S.a;
      ['edge-a','edge-b','add-place','door-map-a','door-map-b'].forEach(id=>populateSelect($(`#${id}`),id==='edge-a'?S.a:id==='edge-b'?S.b:id==='door-map-a'?S.door.a.map:id==='door-map-b'?S.door.b.map:S.b));
      if(initial){const requested=new URLSearchParams(location.search).get('map');if(current(requested))S.a=requested;focusArea(S.a);await setDoorMap('a',S.a,true);if(new URLSearchParams(location.search).get('mode')==='doors')mode('doors');}
      else{for(const name of S.nodes.keys())if(!current(name)){S.nodes.delete(name);S.positions.delete(name);}renderBoard();renderEdgeControls();renderEdgeList();await Promise.all(['a','b'].map(side=>reloadDoor(side)));}
      catalogRows();$('#loading').hidden=true;status();
    }catch(err){$('#loading').hidden=true;error(err.message);toast(err.message,true);$('#source-status').textContent='Could not load';}
  }
  function position(name){return S.positions.get(name)||{x:0,y:0};}
  function snapPosition(a,b,direction,offset){const p=position(a.name);return direction==='up'?{x:p.x+offset,y:p.y-b.height}:direction==='down'?{x:p.x+offset,y:p.y+a.height}:direction==='left'?{x:p.x-b.width,y:p.y+offset}:{x:p.x+a.width,y:p.y+offset};}
  function addNode(name,where){const map=current(name);if(!map)return;if(!S.nodes.has(name)){S.nodes.set(name,true);const a=current(S.a),p=position(S.a);S.positions.set(name,where||{x:p.x+(a?.width||20)+10,y:p.y+5});}}
  function focusArea(name){
    if(!current(name)||S.busy)return;S.a=name;S.nodes.clear();S.positions.clear();addNode(name,{x:0,y:0});
    const links=current(name).connections.filter(link=>directions[link.direction]&&current(link.dest_name));
    links.forEach(link=>addNode(link.dest_name,snapPosition(current(name),current(link.dest_name),link.direction,Number(link.offset)||0)));
    const first=links[0];S.b=first?.dest_name||S.maps.find(map=>map.name!==name&&['MAP_TYPE_ROUTE','MAP_TYPE_TOWN','MAP_TYPE_CITY'].includes(map.map_type))?.name||S.maps.find(map=>map.name!==name)?.name||name;
    if(first){S.direction=first.direction;S.offset=Number(first.offset)||0;}else{S.direction='right';S.offset=0;addNode(S.b);}
    $('#edge-a').value=S.a;$('#edge-b').value=S.b;$('#add-place').value=S.b;renderBoard();renderEdgeControls();renderEdgeList();catalogRows();fitBoard();updateLocation();
  }
  function selectPair(a,b,readExisting=true){if(!current(a)||!current(b)||S.busy)return;S.a=a;S.b=b;addNode(a);addNode(b);if(readExisting){const link=current(a).connections.find(link=>link.dest_name===b&&directions[link.direction]);if(link){S.direction=link.direction;S.offset=Number(link.offset)||0;}else inferArrangement();}$('#edge-a').value=a;$('#edge-b').value=b;renderBoard();renderEdgeControls();renderEdgeList();catalogRows();updateLocation();}
  function updateLocation(){history.replaceState(null,'',`/connections?map=${encodeURIComponent(S.mode==='edges'?S.a:S.door.a.map)}${S.mode==='doors'?'&mode=doors':''}`);}
  function renderBoard(){
    const stage=$('#board-stage');stage.style.width=`${SPAN*S.scale}px`;stage.style.height=`${SPAN*S.scale}px`;const frag=document.createDocumentFragment();
    for(const name of S.nodes.keys()){const map=current(name);if(!map)continue;const p=position(name),card=node('div',`map-node${name===S.a?' active-a':''}${name===S.b?' active-b':''}`);card.dataset.map=name;card.style.left=`${(p.x+ORIGIN)*S.scale}px`;card.style.top=`${(p.y+ORIGIN)*S.scale}px`;card.style.width=`${map.width*S.scale}px`;card.style.height=`${map.height*S.scale}px`;card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label',`${nice(name)}, ${map.width} by ${map.height} tiles. Drag to arrange, click to select destination.`);
      const label=node('div','node-label');label.append(node('span','node-role',name===S.a?'A':name===S.b?'B':'◇'),node('strong','',nice(name)));const start=node('button','node-start','Start here');start.type='button';start.onpointerdown=e=>e.stopPropagation();start.onclick=e=>{e.stopPropagation();selectPair(name,name===S.b?S.a:S.b);};label.append(start);card.append(label);
      const picture=node('div','map-node-image'),image=node('img');image.src=preview(map);image.alt='';image.draggable=false;picture.append(image);if(name===S.a||name===S.b)picture.append(node('span','node-endpoint',name===S.a?'START':'DESTINATION'));card.append(picture,node('span','node-dimensions',`${map.width} × ${map.height} tiles · ${map.warps.length} doors`));
      card.onpointerdown=e=>startDrag(e,name,card);card.onpointermove=e=>moveDrag(e);card.onpointerup=e=>endDrag(e);card.onpointercancel=e=>endDrag(e);card.onlostpointercapture=e=>endDrag(e);card.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();selectPair(S.a,name);}};frag.append(card);
    }
    $('#map-nodes').replaceChildren(frag);drawLines();drawProposal();
  }
  function svgElement(tag,attributes){const element=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(attributes).forEach(([key,value])=>element.setAttribute(key,value));return element;}
  function drawLines(){
    const svg=$('#board-lines');svg.replaceChildren();const seen=new Set();
    for(const name of S.nodes.keys()){const a=current(name),ap=position(name);for(const link of a.connections){if(!S.nodes.has(link.dest_name)||!directions[link.direction])continue;const key=[name,link.dest_name].sort().join('|')+'|'+[link.direction,opposite[link.direction]].sort().join('|');if(seen.has(key))continue;seen.add(key);const b=current(link.dest_name),bp=position(b.name);let x1=ap.x+a.width/2,y1=ap.y+a.height/2,x2=bp.x+b.width/2,y2=bp.y+b.height/2;
      if(link.direction==='up'){y1=ap.y;y2=bp.y+b.height;}else if(link.direction==='down'){y1=ap.y+a.height;y2=bp.y;}else if(link.direction==='left'){x1=ap.x;x2=bp.x+b.width;}else{x1=ap.x+a.width;x2=bp.x;}
      const attrs={x1:(x1+ORIGIN)*S.scale,y1:(y1+ORIGIN)*S.scale,x2:(x2+ORIGIN)*S.scale,y2:(y2+ORIGIN)*S.scale,stroke:link.reciprocal?'#789965':'#b49b52','stroke-width':2};if(!link.reciprocal)attrs['stroke-dasharray']='5 4';svg.append(svgElement('line',attrs));
      for(const [x,y] of [[x1,y1],[x2,y2]])svg.append(svgElement('circle',{cx:(x+ORIGIN)*S.scale,cy:(y+ORIGIN)*S.scale,r:3,fill:link.reciprocal?'#698956':'#b49b52',stroke:'#eef5df','stroke-width':1}));
    }}
  }
  function drawProposal(){const ghost=$('#proposed-map'),a=current(S.a),b=current(S.b);if(!a||!b||a.name===b.name||!Number.isInteger(S.offset)){ghost.hidden=true;return;}const p=snapPosition(a,b,S.direction,S.offset),shown=position(b.name),saved=a.connections.some(link=>link.dest_name===b.name&&link.direction===S.direction&&Number(link.offset)===S.offset&&link.reciprocal);ghost.hidden=saved&&p.x===shown.x&&p.y===shown.y;if(ghost.hidden)return;ghost.style.left=`${(p.x+ORIGIN)*S.scale}px`;ghost.style.top=`${(p.y+ORIGIN)*S.scale}px`;ghost.style.width=`${b.width*S.scale}px`;ghost.style.height=`${b.height*S.scale}px`;}
  function startDrag(event,name,card){if(event.button!==0||S.busy||event.target.closest('button'))return;event.preventDefault();card.setPointerCapture(event.pointerId);const p=position(name);S.drag={name,card,clientX:event.clientX,clientY:event.clientY,start:{...p},moved:false};card.classList.add('dragging');}
  function moveDrag(event){const d=S.drag;if(!d)return;const dx=(event.clientX-d.clientX)/S.scale,dy=(event.clientY-d.clientY)/S.scale;if(Math.abs(dx)+Math.abs(dy)>.5)d.moved=true;const p={x:Math.max(-ORIGIN+10,Math.min(SPAN-ORIGIN-260,Math.round(d.start.x+dx))),y:Math.max(-ORIGIN+10,Math.min(SPAN-ORIGIN-260,Math.round(d.start.y+dy)))};S.positions.set(d.name,p);d.card.style.left=`${(p.x+ORIGIN)*S.scale}px`;d.card.style.top=`${(p.y+ORIGIN)*S.scale}px`;if(d.name!==S.a)S.b=d.name;if(S.a!==S.b)inferArrangement();$('#edge-b').value=S.b;renderEdgeControls();drawLines();drawProposal();}
  function endDrag(){if(!S.drag)return;const drag=S.drag;S.drag=null;drag.card.classList.remove('dragging');if(!drag.moved&&drag.name!==S.a)selectPair(S.a,drag.name);else{renderBoard();renderEdgeControls();} }
  function inferArrangement(){const a=current(S.a),b=current(S.b);if(!a||!b||a===b)return;const ap=position(a.name),bp=position(b.name),dx=(bp.x+b.width/2)-(ap.x+a.width/2),dy=(bp.y+b.height/2)-(ap.y+a.height/2);S.direction=Math.abs(dx)/((a.width+b.width)/2)>Math.abs(dy)/((a.height+b.height)/2)?dx<0?'left':'right':dy<0?'up':'down';S.offset=Math.round(['up','down'].includes(S.direction)?bp.x-ap.x:bp.y-ap.y);}
  function boardBounds(){const values=[...S.nodes.keys()].map(name=>{const p=position(name),m=current(name);return{x:p.x,y:p.y,w:m.width,h:m.height};});if(!values.length)return{x:0,y:0,w:20,h:20};const x=Math.min(...values.map(p=>p.x)),y=Math.min(...values.map(p=>p.y)),r=Math.max(...values.map(p=>p.x+p.w)),b=Math.max(...values.map(p=>p.y+p.h));return{x,y,w:r-x,h:b-y};}
  function fitBoard(){const bounds=boardBounds();S.scale=Math.max(1,Math.min(10,Math.min((viewport.clientWidth-100)/bounds.w,(viewport.clientHeight-110)/bounds.h)));renderBoard();requestAnimationFrame(()=>{viewport.scrollLeft=(bounds.x+ORIGIN+bounds.w/2)*S.scale-viewport.clientWidth/2;viewport.scrollTop=(bounds.y+ORIGIN+bounds.h/2)*S.scale-viewport.clientHeight/2;});}
  function zoomBoard(multiplier){const previous=S.scale;S.scale=Math.max(1,Math.min(14,previous*multiplier));const x=(viewport.scrollLeft+viewport.clientWidth/2)/previous,y=(viewport.scrollTop+viewport.clientHeight/2)/previous;renderBoard();viewport.scrollLeft=x*S.scale-viewport.clientWidth/2;viewport.scrollTop=y*S.scale-viewport.clientHeight/2;}
  function renderEdgeControls(){if(!current(S.a)||!current(S.b))return;$('#edge-a').value=S.a;$('#edge-b').value=S.b;$('#edge-direction').value=S.direction;$('#edge-offset').value=S.offset;const horizontal=['up','down'].includes(S.direction),axis=horizontal?'width':'height',a=current(S.a),b=current(S.b);$('#edge-offset-range').min=1-b[axis];$('#edge-offset-range').max=a[axis]-1;$('#edge-offset-range').value=S.offset;$('#offset-help').textContent=`Positive = ${horizontal?'right':'down'}; negative = ${horizontal?'left':'up'}. Measured in tiles. The return alignment is ${-S.offset}.`;updateEdgeSummary();drawProposal();}
  function edgeValidity(){const a=current(S.a),b=current(S.b);if(!a||!b)return{valid:false,message:'Choose two locations.'};if(a.name===b.name)return{valid:false,message:'Choose two different maps for a walking connection.'};if(!Number.isInteger(S.offset))return{valid:false,message:'Use a whole number of tiles for the offset.'};const horizontal=['up','down'].includes(S.direction),axis=horizontal?'width':'height',depth=horizontal?'height':'width';if(a[depth]<7||b[depth]<7)return{valid:false,message:'Both maps need at least 7 tiles of depth across this walking connection. Use a doorway for smaller rooms.'};const start=Math.max(0,S.offset),end=Math.min(a[axis],S.offset+b[axis]);if(end<=start)return{valid:false,message:'These edges do not overlap. Adjust the offset or move B along the edge.'};return{valid:true,a,b,start,end,overlap:end-start};}
  function updateEdgeSummary(){const v=edgeValidity(),box=$('#edge-summary');box.classList.toggle('warning',!v.valid);box.innerHTML=v.valid?`<strong>${esc(nice(S.a))}</strong> ${arrows[S.direction]} <strong>${esc(nice(S.b))}</strong><br>${v.overlap} tiles overlap along the ${directions[S.direction].toLowerCase()} edge. Return connection included.<br><small>Keep the crossing terrain walkable on both maps.</small>`:esc(v.message);$('#edge-save').disabled=!v.valid||S.busy;const existing=current(S.a)?.connections.some(link=>link.dest_name===S.b&&link.direction===S.direction);$('#edge-disconnect').hidden=!existing;$('#edge-disconnect').disabled=S.busy;}
  function renderEdgeList(){const map=current(S.a);if(!map)return;$('#edge-count').textContent=map.connections.length;const frag=document.createDocumentFragment();map.connections.forEach(link=>{const button=node('button','connection-row');const warning=!link.reciprocal||link.overlap===null;button.innerHTML=`<span class="direction-icon${warning?' warning':''}">${arrows[link.direction]||'↔'}</span><div><strong>${esc(link.dest_name?nice(link.dest_name):'Unresolved destination')}</strong><small>${esc(directions[link.direction]||nice(link.direction))} · offset ${esc(link.offset)}${!link.reciprocal?' · no matching return':''}${directions[link.direction]&&link.overlap===null?' · edges do not meet':''}</small></div><span>›</span>`;button.onclick=()=>{if(!current(link.dest_name)){toast('This link points to an unknown map. Edit its source to repair it.',true);return;}if(!directions[link.direction]){toast('Dive and surface connections are edited in World studio map settings.');return;}S.direction=link.direction;S.offset=Number(link.offset)||0;addNode(link.dest_name,snapPosition(map,current(link.dest_name),S.direction,S.offset));selectPair(S.a,link.dest_name);fitBoard();};frag.append(button);});$('#edge-list').replaceChildren(frag);if(!map.connections.length)$('#edge-list').append(node('p','list-empty','No walking connections yet. Choose another location to create a path.'));const terrain=node('a','terrain-link',`Edit ${nice(S.a)} terrain ↗`);terrain.href=`/world?map=${encodeURIComponent(S.a)}`;$('#edge-list').append(terrain);const area=node('a','terrain-link','Open this town or route workspace ↗');area.href=`/areas?map=${encodeURIComponent(S.a)}`;$('#edge-list').append(area);}
  async function saveEdge(action='connect'){
    if(S.busy)return;const v=edgeValidity();if(action==='connect'&&!v.valid)return;const existing=current(S.a).connections.filter(link=>link.dest_name===S.b&&link.direction===S.direction),reverse=current(S.b).connections.filter(link=>link.dest_name===S.a&&link.direction===opposite[S.direction]),replacing=action==='connect'&&[...existing,...reverse].some(link=>Number(link.offset)!==(existing.includes(link)?S.offset:-S.offset));
    if(action==='disconnect'&&!await dialog('Disconnect these neighbors?',`<p>Remove the ${esc(directions[S.direction].toLowerCase())} walking connection from <strong>${esc(nice(S.a))}</strong> to <strong>${esc(nice(S.b))}</strong>, and its return connection.</p><p>The terrain and doorways stay in place. This saves the source files with backups.</p>`,'Disconnect pair'))return;
    if(replacing&&!await dialog('Change this edge alignment?',`<p>Move the connection between <strong>${esc(nice(S.a))}</strong> and <strong>${esc(nice(S.b))}</strong> to offset <strong>${S.offset}</strong> tiles.</p><p>Both walking directions are updated. Check that the crossing terrain meets at the new position.</p>`,'Update alignment'))return;
    S.busy=true;status();error('');const a=S.a,b=S.b,direction=S.direction,offset=S.offset;
    try{await api('/api/connections/edge',{revision:S.catalog.revision,a,b,direction,offset,action,replace:replacing});S.busy=false;await loadCatalog();if(action==='connect'){S.positions.set(b,snapPosition(current(a),current(b),direction,offset));renderBoard();fitBoard();}toast(action==='connect'?'Walking connection saved in both directions.':'Walking connection and return path removed.');}
    catch(err){error(err.message);toast(err.message,true);}finally{S.busy=false;status();}
  }
  function mode(value){S.mode=value;$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===value));$('#edge-workspace').hidden=value!=='edges';$('#door-workspace').hidden=value!=='doors';$('#edge-inspector').hidden=value!=='edges';$('#door-inspector').hidden=value!=='doors';$('#page-title').textContent=value==='edges'?'What goes where.':'Every door is a new beginning.';$('#page-description').textContent=value==='edges'?'Arrange your places, then connect the paths between them.':'Point to an entrance. Choose where it takes the player.';catalogRows();if(value==='edges')fitBoard();else requestAnimationFrame(()=>{fitDoor('a');fitDoor('b');});updateLocation();}
  async function setDoorMap(side,name,follow=false){
    if(!current(name))return;S.door[side]={map:name,x:null,y:null,elevation:0,index:null};$(`#door-map-${side}`).value=name;
    await reloadDoor(side);
    if(side==='a'&&follow){const first=current(name).warps.find(w=>current(w.dest_name)&&Number.isInteger(w.dest_index)&&w.dest_index>=0);if(first){selectWarp('a',first.index,false);await setDoorMap('b',first.dest_name);if(current(first.dest_name).warps.some(w=>w.index===first.dest_index))selectWarp('b',first.dest_index,false);}else{const target=current(S.b)&&S.b!==name?S.b:S.maps.find(map=>map.name!==name)?.name;if(target)await setDoorMap('b',target);}}
    if(side==='a'){renderDoorList();catalogRows();updateLocation();}renderEndpoints();
  }
  async function reloadDoor(side){
    const endpoint=S.door[side],map=current(endpoint.map);if(!map)return;const request=++S.doorRequests[side];$(`#door-map-${side}`).value=map.name;$(`#door-edit-${side}`).href=`/world?map=${encodeURIComponent(map.name)}`;const select=$(`#door-warp-${side}`);select.replaceChildren();const fresh=node('option','','New door: click a tile');fresh.value='';select.append(fresh);map.warps.forEach(warp=>{const option=node('option','',`Door ${warp.index+1} → ${warp.dest_name?nice(warp.dest_name):warp.dynamic?'story destination':'unresolved'}`);option.value=warp.index;select.append(option);});select.value=endpoint.index===null?'':String(endpoint.index);
    $(`#door-caption-${side}`).textContent='Loading terrain…';S.doorImages[side]=null;
    try{const image=await imageFor(map);if(request!==S.doorRequests[side])return;S.doorImages[side]=image;fitDoor(side);drawDoor(side);}
    catch(err){if(request===S.doorRequests[side])$(`#door-caption-${side}`).textContent=err.message;}
    renderEndpoints();renderDoorList();
  }
  function fitDoor(side){const map=current(S.door[side].map),view=$(`#door-viewport-${side}`);if(!map)return;S.doorZoom[side]=Math.max(.35,Math.min(4,Math.min((view.clientWidth-48)/(map.width*16),(view.clientHeight-48)/(map.height*16))));drawDoor(side);}
  function drawDoor(side){const endpoint=S.door[side],map=current(endpoint.map),image=S.doorImages[side];if(!map||!image)return;const canvas=$(`#door-canvas-${side}`),ctx=canvas.getContext('2d');canvas.width=map.width*16;canvas.height=map.height*16;canvas.style.width=`${canvas.width*S.doorZoom[side]}px`;canvas.style.height=`${canvas.height*S.doorZoom[side]}px`;ctx.imageSmoothingEnabled=false;ctx.drawImage(image,0,0,canvas.width,canvas.height);ctx.textAlign='center';ctx.textBaseline='middle';
    map.warps.forEach(warp=>{const selected=endpoint.index===warp.index,x=Number(warp.x)*16,y=Number(warp.y)*16;ctx.fillStyle=selected?(side==='a'?'#235e44dd':'#a48435ee'):'#517eafe0';ctx.fillRect(x+1,y+1,14,14);ctx.strokeStyle='#ecf6db';ctx.lineWidth=1;ctx.strokeRect(x+.5,y+.5,15,15);ctx.fillStyle='#fff';ctx.font='bold 7px Consolas,monospace';ctx.fillText(String(warp.index+1),x+8,y+8);});
    if(Number.isInteger(endpoint.x)&&Number.isInteger(endpoint.y)){const x=endpoint.x*16,y=endpoint.y*16;ctx.fillStyle=side==='a'?'#3e966a66':'#c8a63f66';ctx.fillRect(x,y,16,16);ctx.strokeStyle='#fff6b8';ctx.lineWidth=2;ctx.strokeRect(x+1,y+1,14,14);ctx.fillStyle='#193928dd';ctx.fillRect(x+3,y+4,10,9);ctx.fillStyle='#fffad2';ctx.font='bold 8px Consolas,monospace';ctx.fillText(side.toUpperCase(),x+8,y+8.5);}
    const warp=map.warps.find(w=>w.index===endpoint.index);$(`#door-caption-${side}`).textContent=Number.isInteger(endpoint.x)?`${endpoint.index===null?'New door':`Door ${endpoint.index+1}`} at tile ${endpoint.x}, ${endpoint.y}${warp?.dest_name?` · currently leads to ${nice(warp.dest_name)}`:warp?.dynamic?' · story-controlled destination':''}`:map.warps.length?`${map.warps.length} existing doors. Click a marker, or an empty tile for a new door.`:'No doors yet. Click a doorway or exit tile to add one.';
  }
  async function selectWarp(side,index,follow=true){const endpoint=S.door[side],map=current(endpoint.map),warp=map?.warps.find(w=>w.index===index);if(!warp)return;S.door[side]={map:map.name,x:Number(warp.x),y:Number(warp.y),elevation:Number(warp.elevation)||0,index:warp.index};$(`#door-warp-${side}`).value=String(warp.index);drawDoor(side);renderEndpoints();
    if(side==='a'&&follow&&current(warp.dest_name)&&Number.isInteger(warp.dest_index)&&warp.dest_index>=0){await setDoorMap('b',warp.dest_name);if(current(warp.dest_name).warps.some(w=>w.index===warp.dest_index))selectWarp('b',warp.dest_index,false);}
  }
  function doorPosition(side,event){const map=current(S.door[side].map),canvas=$(`#door-canvas-${side}`),rect=canvas.getBoundingClientRect();if(!map||!rect.width||!rect.height)return null;const x=Math.floor((event.clientX-rect.left)/rect.width*map.width),y=Math.floor((event.clientY-rect.top)/rect.height*map.height);return x>=0&&y>=0&&x<map.width&&y<map.height?{x,y}:null;}
  function chooseDoor(side,event){if(S.busy||!S.doorImages[side])return;const p=doorPosition(side,event);if(!p)return;const endpoint=S.door[side],map=current(endpoint.map),hits=map.warps.filter(w=>Number(w.x)===p.x&&Number(w.y)===p.y);if(hits.length){const selected=hits.findIndex(w=>w.index===endpoint.index);selectWarp(side,hits[(selected+1)%hits.length].index);return;}S.door[side]={map:map.name,x:p.x,y:p.y,elevation:0,index:null};$(`#door-warp-${side}`).value='';drawDoor(side);renderEndpoints();}
  function renderEndpoints(){const frag=document.createDocumentFragment();for(const side of ['a','b']){const endpoint=S.door[side],map=current(endpoint.map);if(!map)continue;const card=node('section','endpoint-card'),title=node('div','endpoint-title');title.append(node('span',`letter ${side}`,side.toUpperCase()),node('strong','',nice(map.name)));card.append(title,node('p','endpoint-status',Number.isInteger(endpoint.x)?endpoint.index===null?'New doorway':'Existing door '+(endpoint.index+1):'Choose a tile on this map'));const fields=node('div','endpoint-fields');for(const [key,label,max] of [['x','X tile',map.width-1],['y','Y tile',map.height-1],['elevation','Elevation',15]]){const wrap=node('label','field',label),input=node('input');input.type='number';input.id=`endpoint-${side}-${key}`;wrap.htmlFor=input.id;input.setAttribute('aria-label',`${side.toUpperCase()} ${label}`);input.min=0;input.max=max;input.value=endpoint[key]??'';input.disabled=!Number.isInteger(endpoint.x);input.onchange=()=>{if(input.reportValidity()&&input.value!==''){S.door[side][key]=Number(input.value);drawDoor(side);updateDoorSummary();}};wrap.append(input);fields.append(wrap);}card.append(fields);frag.append(card);}$('#endpoint-properties').replaceChildren(frag);updateDoorSummary();}
  function doorValidity(){const a=S.door.a,b=S.door.b;if(!current(a.map)||!current(b.map))return{valid:false,message:'Choose a map at each end.'};if(!Number.isInteger(a.x)||!Number.isInteger(b.x))return{valid:false,message:'Click one doorway tile in each map to choose both endpoints.'};if(a.map===b.map&&a.x===b.x&&a.y===b.y)return{valid:false,message:'Choose two different doorway tiles.'};for(const endpoint of [a,b]){const map=current(endpoint.map);if(!Number.isInteger(endpoint.y)||endpoint.x<0||endpoint.y<0||endpoint.x>=map.width||endpoint.y>=map.height)return{valid:false,message:'Both doorways must be inside their maps.'};}return{valid:true};}
  function updateDoorSummary(){const valid=doorValidity(),box=$('#door-summary');box.classList.toggle('warning',!valid.valid&&Number.isInteger(S.door.a.x));box.innerHTML=valid.valid?`<strong>${esc(nice(S.door.a.map))}</strong><br>↔ <strong>${esc(nice(S.door.b.map))}</strong><br>Both doorways will lead to each other.<br><small>Use doorway / exit terrain at each end; a marker on grass alone does not create a working door.</small>`:esc(valid.message);$('#door-save').disabled=!valid.valid||S.busy;}
  function renderDoorList(){const map=current(S.door.a.map);if(!map)return;$('#door-count').textContent=map.warps.length;const frag=document.createDocumentFragment();map.warps.forEach(warp=>{const button=node('button','connection-row');button.innerHTML=`<span class="direction-icon${!warp.reciprocal?' warning':''}">↪</span><div><strong>Door ${warp.index+1} → ${esc(warp.dest_name?nice(warp.dest_name):warp.dynamic?'Story destination':'Unresolved destination')}</strong><small>Tile ${warp.x}, ${warp.y}${warp.reciprocal?' · return connected':warp.dynamic?' · dynamic warp':' · no matching return'}</small></div><span>›</span>`;button.onclick=()=>selectWarp('a',warp.index);frag.append(button);});$('#door-list').replaceChildren(frag);if(!map.warps.length)$('#door-list').append(node('p','list-empty','This map has no doors. Add one by clicking its entrance tile.'));const terrain=node('a','terrain-link','Paint doorways & edit this map ↗');terrain.href=`/world?map=${encodeURIComponent(map.name)}`;$('#door-list').append(terrain);const area=node('a','terrain-link','Return to the town / route workspace ↗');area.href=`/areas?map=${encodeURIComponent(map.name)}`;$('#door-list').append(area);}
  function existingWarp(endpoint){return current(endpoint.map)?.warps.find(warp=>warp.index===endpoint.index);}
  async function saveDoors(){
    if(S.busy||!doorValidity().valid)return;const a={...S.door.a},b={...S.door.b},aMap=current(a.map),bMap=current(b.map),aIndex=a.index===null?aMap.warps.length:a.index,bIndex=b.index===null?bMap.warps.length+(a.map===b.map&&a.index===null?1:0):b.index;
    const rewired=[];for(const [endpoint,other,index] of [[a,b,bIndex],[b,a,aIndex]]){const old=existingWarp(endpoint);if(old&&(old.dest_name!==other.map||old.dest_index!==index))rewired.push(`${nice(endpoint.map)} door ${endpoint.index+1} currently leads to ${old.dest_name?nice(old.dest_name):old.dynamic?'a story-controlled destination':'an unresolved destination'}.`);}
    const shared=[...new Set([...aMap.events_shared_with,...bMap.events_shared_with])];
    if(rewired.length||shared.length){const result=await dialog('Reconnect these doorways?',`<p><strong>${esc(nice(a.map))}</strong> ↔ <strong>${esc(nice(b.map))}</strong></p>${rewired.map(text=>`<p>${esc(text)}</p>`).join('')}${rewired.length?'<p>The selected doors will lead to each other. Other doors that used to point here stay as they are; review those old paths after reconnecting.</p>':''}${shared.length?`<p>These events are also shared with: ${esc(shared.map(nice).join(', '))}.</p><label><input name="shared" type="checkbox" required>I want to update these shared doorway events.</label>`:''}`,'Connect both directions');if(!result)return;}
    S.busy=true;status();error('');
    try{await api('/api/connections/warp',{revision:S.catalog.revision,a,b,confirm_replace:rewired.length>0,confirm_shared:shared.length>0});S.busy=false;await loadCatalog();const finalA=current(a.map).warps.find(w=>w.x===a.x&&w.y===a.y&&w.elevation===a.elevation&&w.dest_name===b.map),finalB=current(b.map).warps.find(w=>w.x===b.x&&w.y===b.y&&w.elevation===b.elevation&&w.dest_name===a.map);if(finalA)await selectWarp('a',finalA.index,false);if(finalB)await selectWarp('b',finalB.index,false);renderDoorList();toast('Doorways saved. Travel works in both directions when the entrance and exit terrain is set up.');}
    catch(err){error(err.message);toast(err.message,true);}finally{S.busy=false;status();}
  }
  $$('[data-mode]').forEach(button=>button.onclick=()=>mode(button.dataset.mode));$$('[data-filter]').forEach(button=>button.onclick=()=>{S.filter=button.dataset.filter;$$('[data-filter]').forEach(b=>b.classList.toggle('active',b===button));catalogRows();});$('#map-search').oninput=catalogRows;
  $('#edge-a').onchange=e=>{const old=S.a;selectPair(e.target.value,S.b===e.target.value?old:S.b);};$('#edge-b').onchange=e=>selectPair(S.a,e.target.value);
  $('#edge-direction').onchange=e=>{S.direction=e.target.value;renderEdgeControls();};$('#edge-offset').oninput=e=>{S.offset=e.target.value===''?NaN:Number(e.target.value);renderEdgeControls();};$('#edge-offset-range').oninput=e=>{S.offset=Number(e.target.value);renderEdgeControls();};
  $('#add-map').onclick=()=>{if(S.busy)return;const name=$('#add-place').value;addNode(name);selectPair(S.a,name);fitBoard();};$('#show-neighbors').onclick=()=>focusArea(S.a);$('#board-fit').onclick=fitBoard;$('#board-zoom-in').onclick=()=>zoomBoard(1.25);$('#board-zoom-out').onclick=()=>zoomBoard(.8);viewport.addEventListener('wheel',e=>{if(e.ctrlKey){e.preventDefault();zoomBoard(e.deltaY<0?1.12:.89);}},{passive:false});
  $('#edge-save').onclick=()=>saveEdge();$('#edge-disconnect').onclick=()=>saveEdge('disconnect');$('#door-save').onclick=saveDoors;
  for(const side of ['a','b']){$(`#door-map-${side}`).onchange=e=>{if(!S.busy)setDoorMap(side,e.target.value,side==='a');};$(`#door-warp-${side}`).onchange=e=>{if(S.busy)return;if(e.target.value!=='')selectWarp(side,Number(e.target.value));else{const endpoint=S.door[side];S.door[side]={map:endpoint.map,x:null,y:null,elevation:0,index:null};drawDoor(side);renderEndpoints();}};$(`#door-canvas-${side}`).onclick=e=>chooseDoor(side,e);$(`#door-fit-${side}`).onclick=()=>fitDoor(side);$(`#door-viewport-${side}`).addEventListener('wheel',e=>{if(e.ctrlKey){e.preventDefault();S.doorZoom[side]=Math.max(.35,Math.min(6,S.doorZoom[side]*(e.deltaY<0?1.2:.83)));drawDoor(side);}},{passive:false});}
  $('#reload').onclick=async()=>{S.imageVersion++;S.images.clear();await loadCatalog();toast('Connections reloaded from your saved source.');};
  $('#help').onclick=()=>dialog('Make the whole world fit together',`<ul class="tips"><li><strong>Routes &amp; towns:</strong> choose two maps, drag them to sketch an arrangement, then save a north, south, east, or west walking connection.</li><li>Map cards use their actual tile dimensions. Only saved edge direction and alignment affect gameplay; this board’s free positions are planning only.</li><li>A positive offset moves the neighbor right for north/south connections, or down for east/west connections. Return offsets are reversed automatically.</li><li>The edges must overlap, and the matching crossing tiles must be walkable on both maps.</li><li><strong>Doors &amp; stairs:</strong> choose a doorway marker or an empty tile on each map. Connecting saves both destinations together without requiring map IDs.</li><li>A warp marker needs suitable doorway, stair, cave, or exit terrain. A marker on grass alone does not make a working doorway. Paint the needed tiles in Terrain editor.</li><li>Keep all exit markers for a two-tile doorway. Connecting one marker leaves adjacent exit markers unchanged.</li><li>Some original warps intentionally travel one way or use story-controlled destinations. Review the existing purpose before replacing them.</li><li>The <strong>region map</strong> is the PokéNav picture. It does not connect the playable areas.</li><li>Changes are source edits with backups. Build and playtest the game to check arrival positions and story behavior.</li></ul>`,'Got it',true);
  async function init(){try{const session=await api('/api/session');S.token=session.token;await loadCatalog(true);}catch(err){$('#loading').hidden=true;error(err.message);}}init();
})();
