(() => {
  'use strict';
  const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)],clone=v=>JSON.parse(JSON.stringify(v));
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const nice=v=>String(v||'').replace(/_/g,' ').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/\b\w/g,c=>c.toUpperCase());
  const S={token:'',assets:[],character:'brendan',asset:null,baseline:'',dirty:false,busy:false,tool:'brush',color:1,frame:0,zoom:8,history:[],future:[],stroke:null,pan:null,space:false,sheet:null,images:new Map(),dialogResolve:null,toastTimer:null};
  const canvas=$('#editor'),ctx=canvas.getContext('2d'),viewport=$('#viewport');
  const node=(tag,cls='',text)=>{const n=document.createElement(tag);n.className=cls;if(text!==undefined)n.textContent=text;return n;};
  async function api(url,body){const r=await fetch(url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Token':S.token},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(typeof d.error==='string'?d.error:d.error?.message||d.message||`Request failed (${r.status})`);return d;}
  function toast(message,bad=false){clearTimeout(S.toastTimer);$('#toast').textContent=message;$('#toast').classList.toggle('bad',bad);$('#toast').hidden=false;S.toastTimer=setTimeout(()=>$('#toast').hidden=true,bad?9000:5000);}
  function error(message=''){$('#error').textContent=message;$('#error').hidden=!message;}
  function dialog(title,content,submit='Continue',info=false){if($('#dialog').open)return Promise.resolve(null);$('#dialog-title').textContent=title;$('#dialog-content').innerHTML=content;$('#dialog-submit').textContent=submit;$('#dialog-submit').hidden=info;$('#dialog-cancel').textContent=info?'Got it':'Cancel';$('#dialog').showModal();return new Promise(resolve=>S.dialogResolve=resolve);}
  function closeDialog(result){$('#dialog').close();const resolve=S.dialogResolve;S.dialogResolve=null;resolve?.(result);}
  $('#dialog-form').onsubmit=e=>{e.preventDefault();closeDialog(Object.fromEntries(new FormData(e.currentTarget)));};$('#dialog-close').onclick=()=>closeDialog(null);$('#dialog-cancel').onclick=()=>closeDialog(null);$('#dialog').oncancel=e=>{e.preventDefault();closeDialog(null);};
  const snapshot=()=>({pixels:[...S.asset.pixels],palette:[...S.asset.palette]});
  function status(){S.dirty=!!S.asset&&JSON.stringify(snapshot())!==S.baseline;$('#save').disabled=!S.asset||S.busy||!S.dirty;$('#revert').disabled=!S.dirty||S.busy;$('#undo').disabled=!S.history.length||S.busy;$('#redo').disabled=!S.future.length||S.busy;$('#history').disabled=!S.assets.length||S.busy;$('#status').textContent=S.busy?'Opening / saving artwork…':S.dirty?'Unsaved appearance edits':'All changes saved';$$('[data-tool],#import,#export,#zoom-fit,#zoom-in,#zoom-out').forEach(b=>b.disabled=!S.asset||S.busy);$('#palette-option').disabled=!S.asset||S.busy;$('#color-input').disabled=!S.asset||S.busy||S.color===0;document.title=`${S.dirty?'● ':''}Player appearance · Emerald Workbench`;}
  function engineColor(hex){return '#'+hex.slice(1).match(/../g).map(v=>Math.floor((parseInt(v,16)>>3)*255/31).toString(16).padStart(2,'0')).join('');}
  function rgba(hex){return hex.slice(1).match(/../g).map(v=>parseInt(v,16));}
  function getFrame(){const a=S.asset;return a?.frames?.[S.frame]||{index:0,x:0,y:0,width:a?.width||1,height:a?.height||1,label:'Complete artwork'};}
  function getView(){return $('#sheet-view').checked?{x:0,y:0,width:S.asset.width,height:S.asset.height}:getFrame();}
  function rasterize(){if(!S.asset)return;const a=S.asset;S.sheet=document.createElement('canvas');S.sheet.width=a.width;S.sheet.height=a.height;const c=S.sheet.getContext('2d'),data=c.createImageData(a.width,a.height),colors=a.palette.map(color=>rgba(engineColor(color)));for(let i=0;i<a.pixels.length;i++){const p=a.pixels[i],[r,g,b]=colors[p];data.data.set([r,g,b,p===0?0:255],i*4);}c.putImageData(data,0,0);}
  function draw(){if(!S.asset)return;const r=getView(),z=S.zoom;canvas.width=r.width*z;canvas.height=r.height*z;ctx.imageSmoothingEnabled=false;const checker=Math.max(4,z*2);for(let y=0;y<canvas.height;y+=checker)for(let x=0;x<canvas.width;x+=checker){ctx.fillStyle=(Math.floor(x/checker)+Math.floor(y/checker))%2?'#d4dec9':'#e5ebdd';ctx.fillRect(x,y,checker,checker);}ctx.drawImage(S.sheet,r.x,r.y,r.width,r.height,0,0,canvas.width,canvas.height);if($('#grid').checked&&z>=5){ctx.strokeStyle='#38543b23';ctx.lineWidth=.5;ctx.beginPath();for(let x=0;x<=r.width;x++){ctx.moveTo(x*z,0);ctx.lineTo(x*z,canvas.height);}for(let y=0;y<=r.height;y++){ctx.moveTo(0,y*z);ctx.lineTo(canvas.width,y*z);}ctx.stroke();}if($('#sheet-view').checked&&(S.asset.frames||[]).length>1){const f=getFrame();ctx.strokeStyle='#fff8b1';ctx.lineWidth=2;ctx.strokeRect(f.x*z+1,f.y*z+1,f.width*z-2,f.height*z-2);}$('#zoom-fit').textContent=`${z}×`;$('#view-info').textContent=`${r.width} × ${r.height} pixels`;drawPreview();}
  function drawPreview(){if(!S.asset)return;const f=getFrame(),c=$('#preview'),max=Math.max(f.width*3+16,70);c.width=max;c.height=f.height*2+12;const context=c.getContext('2d');context.imageSmoothingEnabled=false;context.drawImage(S.sheet,f.x,f.y,f.width,f.height,0,f.height/2+6,f.width,f.height);context.drawImage(S.sheet,f.x,f.y,f.width,f.height,f.width+12,6,f.width*2,f.height*2);c.style.maxWidth='100%';c.style.height='auto';$('#preview-stage').classList.toggle('dark',$('#preview-dark').checked);}
  function fit(){if(!S.asset)return;const r=getView();S.zoom=Math.max(1,Math.min(32,Math.floor(Math.min((viewport.clientWidth-74)/r.width,(viewport.clientHeight-74)/r.height))));draw();viewport.scrollTop=0;viewport.scrollLeft=0;}
  function zoom(delta){if(!S.asset)return;const r=getView(),old=S.zoom,max=Math.max(1,Math.min(40,Math.floor(8192/Math.max(r.width,r.height))));S.zoom=Math.max(1,Math.min(max,S.zoom+delta));const x=(viewport.scrollLeft+viewport.clientWidth/2)/old,y=(viewport.scrollTop+viewport.clientHeight/2)/old;draw();viewport.scrollLeft=x*S.zoom-viewport.clientWidth/2;viewport.scrollTop=y*S.zoom-viewport.clientHeight/2;}
  function renderFrames(){const a=S.asset;$('#frame-count').textContent=`${a.frames.length} frames · click to edit`;const frag=document.createDocumentFragment();a.frames.forEach((f,i)=>{const b=node('button',`frame${i===S.frame?' active':''}`),c=node('canvas');b.type='button';b.setAttribute('aria-label',f.label||`Frame ${i+1}`);b.title=`${f.label||'Frame '+(i+1)} · ${f.width} × ${f.height}`;c.width=f.width;c.height=f.height;c.getContext('2d').drawImage(S.sheet,f.x,f.y,f.width,f.height,0,0,f.width,f.height);b.append(c,node('span','',i+1));b.onclick=()=>{if(S.busy)return;S.frame=i;renderFrames();fit();};frag.append(b);});$('#frames').replaceChildren(frag);}
  function renderPalette(){const a=S.asset,frag=document.createDocumentFragment();a.palette.forEach((color,i)=>{const b=node('button',`swatch${i===S.color?' active':''}`);b.type='button';b.title=i?`Color ${i} · ${color}`:'Index 0 · transparent';b.setAttribute('aria-label',b.title);b.style.background=i?engineColor(color):'repeating-conic-gradient(#b8c7aa 0 25%,#f1f5e9 0 50%) 0 / 8px 8px';b.append(node('span','',i));b.onclick=()=>{S.color=i;renderPalette();status();};frag.append(b);});$('#palette').replaceChildren(frag);$('#color-label').textContent=S.color?`Color ${S.color}`:'Transparent';$('#color-value').textContent=S.color?`${a.palette[S.color]} → ${engineColor(a.palette[S.color])}`:'Palette index 0';$('#color-input').value=a.palette[S.color];$('#color-preview').style.background=S.color?engineColor(a.palette[S.color]):'repeating-conic-gradient(#b8c7aa 0 25%,#f1f5e9 0 50%) 0 / 8px 8px';const shared=a.palette_shared_with||[];$('#palette-note').textContent=`GBA color channels use 32 shades. Preview shows the game’s resulting color.${shared.length?` This palette is shared by ${shared.length} other artwork entries; saving palette changes asks for confirmation.`:''}`;}
  function renderLibrary(){const query=$('#asset-search').value.toLowerCase(),assets=S.assets.filter(a=>(String(a.character).toLowerCase()===S.character||String(a.character).toLowerCase()==='both')&&(!query||`${a.label} ${a.kind} ${a.variant} ${a.uses?.join(' ')||''}`.toLowerCase().includes(query))),groups=new Map();for(const a of assets){const key=`${a.variant||'Emerald'} · ${nice(a.kind)}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(a);}const frag=document.createDocumentFragment();for(const [key,rows]of [...groups].sort((a,b)=>{const order=['overworld','battle_back','battle_front','icon','intro','credits'];return (a[1][0].variant==='Ruby/Sapphire')-(b[1][0].variant==='Ruby/Sapphire')||order.indexOf(a[1][0].kind)-order.indexOf(b[1][0].kind);})){ const group=node('div','asset-group');group.append(node('h4','',key));for(const a of rows){const b=node('button',`asset-row${S.asset?.path===a.path?' active':''}`),c=node('canvas'),text=node('div');c.width=a.frame_width||a.width;c.height=a.frame_height||a.height;text.append(node('strong','',a.label),node('small','',`${a.frame_count||a.frames?.length||1} frames · ${a.width} × ${a.height}`));b.append(c,text);b.onclick=()=>choose(a.path);b.title=a.path;const url=a.preview_url||`/api/player/preview?path=${encodeURIComponent(a.path)}`;if(!S.images.has(url)){const image=new Image();S.images.set(url,image);image.src=url;}const image=S.images.get(url),drawThumb=()=>{if(!image.naturalWidth)return;const f=a.frames?.[0]||{x:0,y:0,width:c.width,height:c.height};c.getContext('2d').drawImage(image,f.x,f.y,f.width,f.height,0,0,c.width,c.height);};if(image.complete)drawThumb();else image.addEventListener('load',drawThumb,{once:true});group.append(b);}frag.append(group);}if(!assets.length)frag.append(node('p','empty','No matching player artwork.'));$('#asset-list').replaceChildren(frag);$$('[data-character]').forEach(b=>b.classList.toggle('active',b.dataset.character===S.character));}
  function prepareAsset(a){a.frames=a.frames?.length?a.frames:[{index:0,x:0,y:0,width:a.width,height:a.height,label:'Frame 1'}];a.palette=a.palette.map(v=>v.toUpperCase());return a;}
  async function choose(path,palettePath,force=false){if(S.busy)return;if(!force&&S.dirty){const result=await dialog('Keep these appearance edits?',`<p>Save the current sprite before opening another sheet or palette.</p><label><input type="checkbox" name="discard">Discard the pending pixel and color edits instead.</label>`,'Continue');if(!result)return;if(!result.discard&&!await save())return;}S.busy=true;status();error();$('#loading').hidden=false;try{const a=prepareAsset(await api(`/api/player/asset?path=${encodeURIComponent(path)}${palettePath?'&palette_path='+encodeURIComponent(palettePath):''}`));S.asset=a;S.baseline=JSON.stringify(snapshot());S.history=[];S.future=[];S.frame=0;S.stroke=null;S.character=a.character.toLowerCase()==='both'?S.character:a.character.toLowerCase();$('#asset-name').textContent=a.label;$('#asset-info').textContent=`${a.variant||'Emerald'} · ${a.width} × ${a.height} pixels · ${a.frames.length} frames`;$('#palette-option').replaceChildren(...(a.palette_options||[{path:a.palette_path,label:'Original palette'}]).map(option=>{const n=node('option','',option.label);n.value=option.path;n.selected=option.path===a.palette_path;return n;}));rasterize();renderPalette();renderFrames();renderLibrary();fit();}catch(err){error(err.message);toast(err.message,true);}finally{S.busy=false;$('#loading').hidden=true;status();}}
  function commit(before){if(JSON.stringify(before)!==JSON.stringify(snapshot())){S.history.push(before);if(S.history.length>60)S.history.shift();S.future=[];}status();renderFrames();drawPreview();}
  function mutate(fn){if(!S.asset||S.busy)return;const before=snapshot();fn();rasterize();draw();renderPalette();commit(before);}
  function undo(redo=false){if(!S.asset||S.busy)return;const from=redo?S.future:S.history,to=redo?S.history:S.future;if(!from.length)return;to.push(snapshot());Object.assign(S.asset,from.pop());rasterize();draw();renderPalette();renderFrames();status();}
  function position(event){const b=canvas.getBoundingClientRect(),v=getView();return{x:Math.floor((event.clientX-b.left)/S.zoom)+v.x,y:Math.floor((event.clientY-b.top)/S.zoom)+v.y};}
  function inView(p){const r=getView();return p.x>=r.x&&p.y>=r.y&&p.x<r.x+r.width&&p.y<r.y+r.height;}
  function paint(p){if(inView(p))S.asset.pixels[p.y*S.asset.width+p.x]=S.tool==='erase'?0:S.color;}
  function line(a,b){let x=a.x,y=a.y,dx=Math.abs(b.x-a.x),dy=-Math.abs(b.y-a.y),sx=a.x<b.x?1:-1,sy=a.y<b.y?1:-1,e=dx+dy,guard=0;while(guard++<4096){paint({x,y});if(x===b.x&&y===b.y)break;const e2=e*2;if(e2>=dy){e+=dy;x+=sx;}if(e2<=dx){e+=dx;y+=sy;}}}
  function fill(p){const a=S.asset,old=a.pixels[p.y*a.width+p.x],replacement=S.color;if(old===replacement)return;const stack=[p],seen=new Set();while(stack.length){const q=stack.pop(),i=q.y*a.width+q.x;if(!inView(q)||seen.has(i)||a.pixels[i]!==old)continue;seen.add(i);a.pixels[i]=replacement;stack.push({x:q.x-1,y:q.y},{x:q.x+1,y:q.y},{x:q.x,y:q.y-1},{x:q.x,y:q.y+1});}}
  function pick(p){if(!inView(p))return;S.color=S.asset.pixels[p.y*S.asset.width+p.x];renderPalette();status();}
  canvas.onpointerdown=event=>{if(!S.asset||S.busy)return;event.preventDefault();canvas.setPointerCapture(event.pointerId);if(S.space||event.button===1){S.pan={x:event.clientX,y:event.clientY,left:viewport.scrollLeft,top:viewport.scrollTop};viewport.classList.add('panning');return;}const p=position(event);if(!inView(p))return;if(event.button===2||S.tool==='picker'){pick(p);return;}if(event.button!==0)return;if(S.tool==='fill'){mutate(()=>fill(p));return;}S.stroke={before:snapshot(),last:p};paint(p);rasterize();draw();};
  canvas.onpointermove=event=>{if(!S.asset)return;if(S.pan){viewport.scrollLeft=S.pan.left-(event.clientX-S.pan.x);viewport.scrollTop=S.pan.top-(event.clientY-S.pan.y);return;}const p=position(event);if(inView(p))$('#coordinates').textContent=`Pixel ${p.x}, ${p.y} · palette index ${S.asset.pixels[p.y*S.asset.width+p.x]}`;if(S.stroke){line(S.stroke.last,p);S.stroke.last=p;rasterize();draw();}};
  function finish(){S.pan=null;viewport.classList.remove('panning');if(S.stroke){const before=S.stroke.before;S.stroke=null;commit(before);}}
  canvas.onpointerup=finish;canvas.onpointercancel=finish;canvas.onlostpointercapture=finish;canvas.oncontextmenu=e=>e.preventDefault();viewport.addEventListener('wheel',e=>{if(!S.asset)return;e.preventDefault();zoom(e.deltaY<0?1:-1);},{passive:false});
  async function save(){if(!S.asset||S.busy)return false;finish();if(!S.dirty)return true;const original=JSON.parse(S.baseline),paletteChanged=JSON.stringify(original.palette)!==JSON.stringify(S.asset.palette),shared=S.asset.palette_shared_with||[];let confirmed=false;if(paletteChanged&&shared.length){const result=await dialog('Save this shared player palette?',`<p>The new colors will also change these player artwork entries:</p><div class="file-list">${shared.map(a=>`<div>${esc(a.label||a.path)}</div>`).join('')}</div><label><input type="checkbox" required name="confirm">Apply these palette colors to the shared player artwork.</label>`,'Save appearance');if(!result)return false;confirmed=true;}S.busy=true;status();error();try{const response=await api('/api/player/save',{path:S.asset.path,palette_path:S.asset.palette_path,revision:S.asset.revision,pixels:S.asset.pixels,palette:S.asset.palette,confirm_shared:confirmed});S.asset=prepareAsset(response.asset);S.baseline=JSON.stringify(snapshot());S.history=[];S.future=[];S.images.clear();rasterize();draw();renderPalette();renderFrames();renderLibrary();toast(response.message||'Player appearance saved with backups.');return true;}catch(err){error(err.message);toast(err.message,true);return false;}finally{S.busy=false;status();}}
  async function importPNG(file){
    if(!S.asset||!file||S.busy)return;const target=S.asset;
    try{
      const signature=new Uint8Array(await file.slice(0,8).arrayBuffer());
      if([137,80,78,71,13,10,26,10].some((byte,i)=>signature[i]!==byte))throw Error('Choose a PNG file. Other image formats are not imported.');
      const image=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(Error('The PNG file could not be opened.'));reader.onload=()=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error('This file could not be read as a PNG image.'));img.src=reader.result;};reader.readAsDataURL(file);});
      if(S.asset!==target)throw Error('The selected sheet changed while the PNG was opening. Import it again for the desired sheet.');
      if(image.width!==target.width||image.height!==target.height)throw Error(`Use a complete ${target.width} × ${target.height} pixel sprite sheet. This image is ${image.width} × ${image.height}.`);
      const c=document.createElement('canvas');c.width=image.width;c.height=image.height;const context=c.getContext('2d');context.drawImage(image,0,0);
      const data=context.getImageData(0,0,c.width,c.height).data,colors=new Map(),source=[];
      for(let i=0;i<data.length;i+=4){const alpha=data[i+3];if(alpha!==0&&alpha!==255)throw Error('Partly transparent pixels are not supported. Use only fully opaque or fully transparent pixels.');if(!alpha){source.push(null);continue;}const color='#'+[data[i],data[i+1],data[i+2]].map(v=>v.toString(16).padStart(2,'0')).join('').toUpperCase();colors.set(color,true);source.push(color);}
      if(colors.size>15)throw Error(`This PNG contains ${colors.size} opaque colors. Player artwork supports at most 15 opaque colors plus transparency. Reduce its colors deliberately before importing.`);
      const palette=[...target.palette],engine=palette.map(color=>engineColor(color).toUpperCase()),lookup=new Map();
      palette.forEach((color,i)=>{if(i){if(!lookup.has(color.toUpperCase()))lookup.set(color.toUpperCase(),i);if(!lookup.has(engine[i]))lookup.set(engine[i],i);}});
      // Keep duplicate color indices on unchanged pixels; source colors and GBA-expanded colors both match.
      const pixels=source.map((color,i)=>{if(color===null)return 0;const original=target.pixels[i];return original>0&&(color===palette[original].toUpperCase()||color===engine[original])?original:lookup.get(color);});
      const used=new Set(pixels.filter(index=>Number.isInteger(index)&&index>0)),unmatched=[...colors.keys()].filter(color=>!lookup.has(color)),available=Array.from({length:15},(_,i)=>i+1).filter(i=>!used.has(i));
      if(unmatched.length>available.length)throw Error(`This image needs ${unmatched.length} new palette entries, but only ${available.length} are available while preserving its matching color indices. Reuse an existing color or free a palette entry before importing.`);
      if(unmatched.length){
        const result=await dialog('Add this PNG’s new colors?',`<p>The dimensions are correct. This image uses ${colors.size} opaque colors, including ${unmatched.length} new colors.</p><p>Matching colors keep their existing palette entries. The new colors will replace ${unmatched.length} available entries that the imported pixels do not need. Other sheets sharing those entries may also change when saved.</p><p>The GBA uses 32 shades per color channel; the preview shows the resulting colors.</p><label><input type="checkbox" name="adopt" required>Add these new colors to the available palette entries.</label>`,'Import pixels & colors');
        if(!result)return;unmatched.forEach((color,i)=>{const index=available[i];palette[index]=color;lookup.set(color,index);});
      }else if(!await dialog('Import this player sprite sheet?',`<p>${image.width} × ${image.height} pixels · ${colors.size} opaque colors. Every color matches the active palette.</p><p>Matching pixels retain their palette indices. You can undo the import before saving.</p>`,'Import pixels'))return;
      mutate(()=>{S.asset.palette=palette;S.asset.pixels=pixels.map((index,i)=>index===undefined?lookup.get(source[i]):index);});toast('PNG imported. Review the frames, then save appearance.');
    }catch(err){toast(err.message,true);}finally{$('#import-file').value='';}
  }
  function exportPNG(){if(!S.asset)return;const asset=S.asset,c=document.createElement('canvas');c.width=S.asset.width;c.height=S.asset.height;const context=c.getContext('2d'),d=context.createImageData(c.width,c.height);S.asset.pixels.forEach((index,i)=>d.data.set([...rgba(S.asset.palette[index]),index?255:0],i*4));context.putImageData(d,0,0);const filename=(asset.label+'_'+(asset.palette_options?.find(option=>option.path===asset.palette_path)?.label||'palette')).replace(/[^a-zA-Z0-9_-]/g,'_')+'.png',download=$('#export-link');download.href=c.toDataURL('image/png');download.download=filename;download.hidden=false;download.title=filename;c.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download=filename;a.hidden=true;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('PNG prepared. Use the download link below Export if the automatic download did not start.');},'image/png');}
  async function history(){if(S.busy||!S.asset)return;if(S.dirty&&!await save())return;try{const {transactions}=await api('/api/transactions'),allowed=new Set(S.assets.flatMap(a=>[a.path,a.palette_path,...(a.palette_options||[]).map(option=>option.path)])),matches=transactions.filter(t=>t.files.some(p=>allowed.has(String(p))));if(!matches.length){await dialog('Player artwork history','<p>Saved player artwork changes will appear here. Each save keeps a backup of the previous source files.</p>','Got it',true);return;}const pending=dialog('Restore saved artwork',`<p>Restore a previous save’s changed files. If later saves touch the same files, restore those newer saves first.</p><label for="history-choice">Saved edit</label><select id="history-choice" name="transaction">${matches.map(t=>`<option value="${esc(t.id)}">${esc(t.label)} · ${t.files.length} files</option>`).join('')}</select><div id="history-files" class="file-list"></div>`,'Restore previous files');const show=()=>{const t=matches.find(t=>t.id===$('#history-choice').value);$('#history-files').replaceChildren(...t.files.map(p=>node('div','',p)));};$('#history-choice').onchange=show;show();const result=await pending;if(!result)return;S.busy=true;status();await api('/api/transaction/undo',{id:result.transaction});S.images.clear();const path=S.asset.path,palette=S.asset.palette_path;S.busy=false;await choose(path,palette,true);toast('Previous artwork files restored.');}catch(err){toast(err.message,true);}finally{S.busy=false;status();}}
  $$('[data-character]').forEach(b=>b.onclick=()=>{if(S.busy)return;S.character=b.dataset.character;renderLibrary();});$('#asset-search').oninput=renderLibrary;
  $$('[data-tool]').forEach(b=>b.onclick=()=>{S.tool=b.dataset.tool;$$('[data-tool]').forEach(n=>n.classList.toggle('active',n===b));});$('#color-input').onchange=e=>mutate(()=>{S.asset.palette[S.color]=e.target.value.toUpperCase();});$('#palette-option').onchange=async e=>{const current=S.asset.palette_path;await choose(S.asset.path,e.target.value);$('#palette-option').value=S.asset.palette_path||current;};
  $('#save').onclick=save;$('#undo').onclick=()=>undo();$('#redo').onclick=()=>undo(true);$('#zoom-fit').onclick=fit;$('#zoom-in').onclick=()=>zoom(1);$('#zoom-out').onclick=()=>zoom(-1);$('#sheet-view').onchange=fit;$('#grid').onchange=draw;$('#preview-dark').onchange=drawPreview;$('#import').onclick=()=>$('#import-file').click();$('#import-file').onchange=e=>importPNG(e.target.files[0]);$('#export').onclick=exportPNG;$('#history').onclick=history;
  $('#revert').onclick=async()=>{if(!await dialog('Revert pending appearance edits?','<p>Return this sheet and palette to the last saved version.</p>','Revert edits'))return;Object.assign(S.asset,JSON.parse(S.baseline));S.history=[];S.future=[];rasterize();draw();renderPalette();renderFrames();status();};
  document.addEventListener('keydown',e=>{if($('#dialog').open)return;const typing=/INPUT|TEXTAREA|SELECT/.test(e.target.tagName);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save();return;}if(typing)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey);return;}if(e.code==='Space'){e.preventDefault();S.space=true;}const tool={b:'brush',e:'erase',f:'fill',i:'picker'}[e.key.toLowerCase()];if(tool&&!e.ctrlKey&&!e.metaKey)$(`[data-tool="${tool}"]`)?.click();});document.addEventListener('keyup',e=>{if(e.code==='Space')S.space=false;});window.addEventListener('blur',()=>{S.space=false;finish();});window.addEventListener('beforeunload',e=>{if(S.dirty){e.preventDefault();e.returnValue='';}});
  document.addEventListener('click',async e=>{const link=e.target.closest('a[href]');if(!link||link.hasAttribute('download')||!S.dirty||e.ctrlKey||e.metaKey||link.target==='_blank')return;e.preventDefault();if(await dialog('Leave pending appearance edits?','<p>Save appearance to keep these pixel and palette edits.</p>','Discard and leave')){S.dirty=false;location.href=link.href;}});
  async function init(){try{const[session,catalog]=await Promise.all([api('/api/session'),api('/api/player')]);S.token=session.token;S.assets=catalog.assets;renderLibrary();const params=new URLSearchParams(location.search),requested=params.get('path');const first=S.assets.find(a=>a.path===requested)||S.assets.find(a=>a.path==='graphics/object_events/pics/people/brendan/walking.png')||S.assets.find(a=>a.character==='Brendan'&&a.variant==='Emerald')||S.assets[0];if(first)await choose(first.path,params.get('palette_path'),true);else throw Error('No editable player artwork was found.');}catch(err){error(err.message);$('#loading').hidden=true;status();}}
  init();
})();
