(() => {
'use strict';
const $=s=>document.querySelector(s), canvas=$('#map'), ctx=canvas.getContext('2d'), atlas=$('#atlas'), ac=atlas.getContext('2d');
let data, image, token='', tile=0, dirty=false, drawing=false, undo=[], redo=[], baseline='';
const clone=x=>JSON.parse(JSON.stringify(x));
async function api(url,body){const response=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Token':token},body:JSON.stringify(body)}:{});const result=await response.json();if(!response.ok)throw Error(result.error||'Request failed');return result;}
function error(e){$('#error').textContent=e.message;$('#error').hidden=false;}
function editable(){return {cells:data.cells,section_cells:data.section_cells,sections:data.sections};}
function status(){dirty=JSON.stringify(editable())!==baseline;$('#save').disabled=!dirty;$('#undo').disabled=!undo.length;$('#redo').disabled=!redo.length;$('#status').textContent=dirty?'Unsaved changes':'Saved source';document.title=(dirty?'• ':'')+'Region map · Emerald Workbench';}
function checkpoint(){undo.push(clone(editable()));if(undo.length>50)undo.shift();redo=[];}
function restore(value){Object.assign(data,value);sectionFields();draw();status();}
function dimensions(){return $('#mode').value==='art'?[64,64,8]:[28,15,18];}
function color(id){if(id==='MAPSEC_NONE')return '#e5ece4';let n=0;for(const c of id)n=(n*31+c.charCodeAt(0))|0;return `hsl(${Math.abs(n)%360} 36% 75%)`;}
function draw(){if(!data||!image)return;const art=$('#mode').value==='art', [w,h,size]=dimensions(),zoom=Number($('#zoom').value);canvas.width=w*size;canvas.height=h*size;canvas.style.width=canvas.width*zoom+'px';canvas.style.height=canvas.height*zoom+'px';ctx.imageSmoothingEnabled=false;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const index=y*w+x;if(art){const id=data.cells[index];ctx.drawImage(image,(id%16)*8,Math.floor(id/16)*8,8,8,x*size,y*size,size,size);}else{ctx.fillStyle=color(data.section_cells[index]);ctx.fillRect(x*size,y*size,size,size);if(data.section_cells[index]===$('#section').value){ctx.strokeStyle='#173e33';ctx.lineWidth=2;ctx.strokeRect(x*size+2,y*size+2,size-4,size-4);}}}if($('#grid').checked){ctx.strokeStyle=art?'#ffffff20':'#ffffff90';ctx.lineWidth=.5;ctx.beginPath();for(let x=0;x<=w;x++){ctx.moveTo(x*size,0);ctx.lineTo(x*size,h*size);}for(let y=0;y<=h;y++){ctx.moveTo(0,y*size);ctx.lineTo(w*size,y*size);}ctx.stroke();}$('#tiles-panel').hidden=!art;$('#explanation').textContent=art?'Actual 64 × 64 affine tilemap used by the PokéNav. Palette and tile pixels stay original.':'28 × 15 named-location grid. Colors distinguish location IDs; the artwork is edited on its own layer.';}
function drawAtlas(){atlas.width=128;atlas.height=120;ac.imageSmoothingEnabled=false;ac.drawImage(image,0,0);ac.strokeStyle='#ff4c57';ac.lineWidth=1;ac.strokeRect(tile%16*8+.5,Math.floor(tile/16)*8+.5,7,7);$('#tile-label').textContent='Tile '+tile+' of 232';}
function point(event){const r=canvas.getBoundingClientRect(),[w,h,size]=dimensions();const x=Math.floor((event.clientX-r.left)*canvas.width/r.width/size),y=Math.floor((event.clientY-r.top)*canvas.height/r.height/size);return x>=0&&y>=0&&x<w&&y<h?{x,y,index:y*w+x,w,h}:null;}
function pick(p){if($('#mode').value==='art'){tile=data.cells[p.index];drawAtlas();}else{$('#section').value=data.section_cells[p.index];sectionFields();draw();}}
function paint(p,fill=false){const art=$('#mode').value==='art', cells=art?data.cells:data.section_cells, value=art?tile:$('#section').value, old=cells[p.index];if(old===value)return;if(fill){const pending=[p.index];cells[p.index]=value;while(pending.length){const i=pending.pop(),x=i%p.w,y=Math.floor(i/p.w);for(const n of [x>0?i-1:-1,x+1<p.w?i+1:-1,y>0?i-p.w:-1,y+1<p.h?i+p.w:-1])if(n>=0&&cells[n]===old){cells[n]=value;pending.push(n);}}}else cells[p.index]=value;draw();status();}
canvas.addEventListener('contextmenu',e=>e.preventDefault());
canvas.addEventListener('pointerdown',e=>{if(!data)return;const p=point(e);if(!p)return;if(e.button===2||$('#tool').value==='pick'){pick(p);return;}checkpoint();drawing=true;canvas.setPointerCapture(e.pointerId);paint(p,$('#tool').value==='fill');if($('#tool').value==='fill')drawing=false;});
canvas.addEventListener('pointermove',e=>{const p=point(e);if(!p)return;$('#cursor').textContent=`${p.x}, ${p.y} · ${$('#mode').value==='art'?'tile '+data.cells[p.index]:data.section_cells[p.index]}`;if(drawing)paint(p);});
canvas.addEventListener('pointerup',()=>drawing=false);canvas.addEventListener('pointercancel',()=>drawing=false);
atlas.addEventListener('pointerdown',e=>{const r=atlas.getBoundingClientRect();const id=Math.floor((e.clientY-r.top)/r.height*15)*16+Math.floor((e.clientX-r.left)/r.width*16);if(id>=0&&id<233){tile=id;drawAtlas();}});
function sectionFields(){const section=data.sections.find(s=>s.id===$('#section').value), none=!section;$('#section-name').value=section?.name||'';$('#section-name').disabled=none;for(const key of ['x','y','width','height']){$('#section-'+key).value=section?.[key]??0;$('#section-'+key).disabled=none;}$('#update-section').disabled=none;}
$('#section').addEventListener('change',()=>{sectionFields();draw();});
$('#update-section').addEventListener('click',()=>{const section=data.sections.find(s=>s.id===$('#section').value);if(!section)return;const values={name:$('#section-name').value};for(const key of ['x','y','width','height']){values[key]=Number($('#section-'+key).value);if(!Number.isInteger(values[key])||values[key]<0||values[key]>255){error(Error('Location values must be integers from 0 to 255.'));return;}}checkpoint();Object.assign(section,values);draw();status();});
for(const id of ['mode','zoom','grid'])$('#'+id).addEventListener('change',draw);
$('#undo').addEventListener('click',()=>{if(undo.length){redo.push(clone(editable()));restore(undo.pop());}});$('#redo').addEventListener('click',()=>{if(redo.length){undo.push(clone(editable()));restore(redo.pop());}});
async function load(){data=await api('/api/region');image=new Image();image.src=data.atlas_url;await image.decode();const select=$('#section');select.replaceChildren();for(const s of [{id:'MAPSEC_NONE',name:'Empty / no location'},...data.sections]){const option=document.createElement('option');option.value=s.id;option.textContent=s.name||s.id;select.append(option);}baseline=JSON.stringify(editable());undo=[];redo=[];sectionFields();drawAtlas();draw();status();}
$('#reload').addEventListener('click',async()=>{if(dirty){const dialog=$('#confirm');dialog.returnValue='cancel';dialog.showModal();if(await new Promise(r=>dialog.addEventListener('close',()=>r(dialog.returnValue),{once:true}))!=='yes')return;}try{await load();}catch(e){error(e);}});
$('#save').addEventListener('click',async()=>{$('#error').hidden=true;$('#save').disabled=true;try{const result=await api('/api/region',{revision:data.revision,...editable()});data=result;baseline=JSON.stringify(editable());status();$('#status').textContent='Region saved with backups';}catch(e){error(e);status();}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
(async()=>{try{token=(await api('/api/session')).token;await load();}catch(e){error(e);$('#status').textContent='Unable to load';}})();
})();
