(() => {
  'use strict';
  if(window.parent!==window&&window.parent.WorldTools){window.parent.WorldTools.returnToWorld(new URLSearchParams(location.search).get('map'));return;}
  const $=(q,root=document)=>root.querySelector(q), $$=(q,root=document)=>[...root.querySelectorAll(q)];
  const clone=value=>JSON.parse(JSON.stringify(value));
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const nice=v=>String(v||'').replace(/^OBJ_EVENT_GFX_|^MAP_/,'').replace(/([a-z\d])([A-Z])/g,'$1 $2').replace(/([A-Za-z])(\d+)/g,'$1 $2').replace(/_/g,' ');
  const eventKinds=['object_events','warp_events','coord_events','bg_events'];
  const eventLabels={object_events:'Person / object',warp_events:'Doorway / warp',coord_events:'Story trigger',bg_events:'Sign / interaction'};
  const eventLetters={object_events:'N',warp_events:'W',coord_events:'T',bg_events:'S'};
  const eventColors={object_events:'#3d8655',warp_events:'#5489b6',coord_events:'#bc913d',bg_events:'#9d73b1'};
  const categories=[{id:'town',label:'Towns & cities',color:'#7f9b64'},{id:'route',label:'Routes',color:'#779da1'},{id:'dungeon',label:'Caves & landmarks',color:'#aa9771'},{id:'special',label:'Other areas',color:'#9985a0'}];
  const S={ready:false,busy:false,finishing:false,token:'',catalog:null,maps:[],byName:new Map(),areas:[],areaByMap:new Map(),objects:[],objectById:new Map(),
    buffers:new Map(),loads:new Map(),atlases:new Map(),previews:new Map(),sprites:new Map(),selected:null,selectionRequest:0,panel:'tiles',mode:'terrain',tool:'select',
    tile:0,erasers:new Map(),object:'OBJ_EVENT_GFX_BOY_1',place:false,event:null,camera:{x:0,y:0},scale:1,width:1,height:1,dpr:1,space:false,drag:null,hover:null,
    history:[],future:[],frame:null,toastTimer:null,dialogResolve:null,preloadDone:0,previewDone:0,minimap:null,pointerActive:null,press:0,generation:0,
    category:'all',openCategories:new Set(),openAreas:new Set(),previewRunning:-1,previewInFlight:new Set(),previewFailed:new Set(),viewportLoadTimer:null};
  const viewport=$('#world-viewport'),canvas=$('#world-canvas'),ctx=canvas.getContext('2d');
  function node(tag,cls='',text){const n=document.createElement(tag);n.className=cls;if(text!==undefined)n.textContent=text;return n;}
  async function api(url,body){const res=await fetch(url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Token':S.token},body:JSON.stringify(body)});let data;try{data=await res.json();}catch{throw new Error(`The server returned an unreadable response (${res.status}).`);}if(!res.ok)throw new Error(typeof data.error==='string'?data.error:data.error?.message||data.message||`Request failed (${res.status}).`);return data;}
  function toast(message,bad=false){clearTimeout(S.toastTimer);$('#toast').textContent=message;$('#toast').classList.toggle('error',bad);$('#toast').hidden=false;S.toastTimer=setTimeout(()=>$('#toast').hidden=true,bad?8000:4500);}
  function error(message=''){$('#error').textContent=message;$('#error').hidden=!message;}
  function map(name=S.selected){return S.byName.get(name);}
  function buffer(name=S.selected){return S.buffers.get(name);}
  function categoryOf(row){return row.area_kind||S.areaByMap.get(row.name)?.kind||'special';}
  function included(row){return S.category==='all'||categoryOf(row)===S.category;}
  function mapTitle(row,full=true){const area=row.area_name||S.areaByMap.get(row.name)?.name,short=row.display_name||nice(row.name);return full&&area&&short!==area?`${area} · ${short}`:short;}
  function boundsOf(rows){if(!rows.length)return S.catalog?.bounds;const x=Math.min(...rows.map(row=>row.x)),y=Math.min(...rows.map(row=>row.y)),right=Math.max(...rows.map(row=>row.x+row.width)),bottom=Math.max(...rows.map(row=>row.y+row.height));return{x,y,width:right-x,height:bottom-y};}
  function dirtyBuffers(){return [...S.buffers.values()].filter(b=>b.dirty);}
  function snapshot(b){return clone({width:b.data.width,height:b.data.height,cells:b.data.cells,border:b.data.border,map:b.data.map,layout:b.data.layout});}
  function fingerprint(b){return JSON.stringify(snapshot(b));}
  function updateDirty(b){b.dirty=fingerprint(b)!==b.saved;}
  function status(){const dirty=dirtyBuffers(),working=S.busy||S.finishing;$('#save-world').disabled=!S.ready||working||!dirty.length;$('#save-world').firstChild.textContent=dirty.length?`Save ${dirty.length===1?'world':dirty.length+' places'} `:'Save world ';$('#save-status').textContent=working?'Saving / finishing edits…':dirty.length?`${dirty.length} place${dirty.length===1?' has':'s have'} unsaved changes`:'All changes saved';$('#dirty-count').textContent=dirty.length?`${dirty.length} edited places`:'No unsaved changes';$('#undo').disabled=!S.history.length||working;$('#redo').disabled=!S.future.length||working;$('#saved-history').disabled=!S.ready||working;$('#new-place').disabled=!S.ready||working;const ready=S.maps.filter(row=>S.previews.has(row.name)||buffer(row.name)?.raster).length;$('#load-status').textContent=ready<S.maps.length?`${ready} / ${S.maps.length} map previews loaded`:`${S.maps.length} maps · all artwork ready`;$('#world-count').textContent=S.catalog?`${S.maps.length} MAPS · ${S.areas.length} AREAS · ONE CANVAS`:'ALL AREAS. ONE EDITABLE WORLD.';document.title=`${dirty.length?'● ':''}Your World · Emerald Workbench`;}
  function dialog(title,html,submit='Continue',info=false){if($('#dialog').open)return Promise.resolve(null);$('#dialog-title').textContent=title;$('#dialog-content').innerHTML=html;$('#dialog-submit').textContent=submit;$('#dialog-submit').hidden=info;$('#dialog-cancel').textContent=info?'Got it':'Cancel';$('#dialog').showModal();return new Promise(resolve=>S.dialogResolve=resolve);}
  function closeDialog(value){$('#dialog').close();const resolve=S.dialogResolve;S.dialogResolve=null;if(resolve)resolve(value);}
  $('#dialog-form').onsubmit=e=>{e.preventDefault();closeDialog(Object.fromEntries(new FormData(e.currentTarget)));};$('#dialog-close').onclick=()=>closeDialog(null);$('#dialog-cancel').onclick=()=>closeDialog(null);$('#dialog').oncancel=e=>{e.preventDefault();closeDialog(null);};
  function loadImage(url){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('Some map artwork could not be loaded. Reload the editor to try again.'));image.src=url;});}
  function atlasFor(data){const key=`${data.tileset.primary||data.layout.primary_tileset}|${data.tileset.secondary||data.layout.secondary_tileset}`;if(!S.atlases.has(key))S.atlases.set(key,loadImage(data.tileset.atlas_url));return S.atlases.get(key);}
  async function ensureBuffer(name){
    if(S.buffers.has(name))return S.buffers.get(name);if(S.loads.has(name))return S.loads.get(name);
    const generation=S.generation;const promise=(async()=>{const data=await api(`/api/world/map?name=${encodeURIComponent(name)}`),atlas=await atlasFor(data);eventKinds.forEach(kind=>data.map[kind]||=[]);const b={data,atlas,raster:null,dirty:false,saved:'',valid:new Set(data.tileset.metatiles.filter(t=>t.valid!==false).map(t=>t.id))};b.saved=fingerprint(b);if(generation!==S.generation)return b;S.buffers.set(name,b);
      const counts=new Map();data.cells.forEach(value=>{const id=value&1023;if(b.valid.has(id))counts.set(id,(counts.get(id)||0)+1);});S.erasers.set(name,[...counts].sort((a,b)=>b[1]-a[1])[0]?.[0]||[...b.valid][0]||0);S.preloadDone=S.buffers.size;status();render();return b;})();
    S.loads.set(name,promise);try{return await promise;}finally{if(S.loads.get(name)===promise)S.loads.delete(name);}
  }
  function drawTile(context,b,id,x,y,size=16){const cols=b.data.tileset.columns||16;context.imageSmoothingEnabled=false;context.drawImage(b.atlas,(id%cols)*16,Math.floor(id/cols)*16,16,16,x,y,size,size);}
  function rasterize(b){if(!b.raster){b.raster=document.createElement('canvas');b.raster.width=b.data.width*16;b.raster.height=b.data.height*16;}const context=b.raster.getContext('2d');context.imageSmoothingEnabled=false;context.fillStyle='#b4ce95';context.fillRect(0,0,b.raster.width,b.raster.height);b.data.cells.forEach((value,i)=>drawTile(context,b,value&1023,(i%b.data.width)*16,Math.floor(i/b.data.width)*16));return b.raster;}
  function updateTileRaster(b,i){if(!b.raster)return;const context=b.raster.getContext('2d'),x=(i%b.data.width)*16,y=Math.floor(i/b.data.width)*16;context.clearRect(x,y,16,16);context.fillStyle='#b4ce95';context.fillRect(x,y,16,16);drawTile(context,b,b.data.cells[i]&1023,x,y);}
  async function preload(){
    const generation=S.generation;if(S.previewRunning===generation)return;S.previewRunning=generation;
    function priority(row){return(row.name===S.selected?-1e9:visible(row)&&included(row)?-1e8:included(row)?-1e6:0)+Math.hypot(row.x+row.width/2-S.camera.x,row.y+row.height/2-S.camera.y);}
    await Promise.all(Array.from({length:3},async()=>{while(generation===S.generation){const row=S.maps.filter(row=>!S.previews.has(row.name)&&!S.previewInFlight.has(row.name)&&!S.previewFailed.has(row.name)).sort((a,b)=>priority(a)-priority(b))[0];if(!row)return;S.previewInFlight.add(row.name);try{const url=row.preview_url||`/api/world/maps/${row.name}/preview.png`;const image=await loadImage(`${url}${url.includes('?')?'&':'?'}max_size=256`);if(generation===S.generation)S.previews.set(row.name,image);}catch{if(generation===S.generation)S.previewFailed.add(row.name);}finally{if(generation===S.generation){S.previewInFlight.delete(row.name);status();render();}}}}));
    if(generation===S.generation)S.previewRunning=-1;
  }
  function scheduleNearbyBuffers(){clearTimeout(S.viewportLoadTimer);if(!S.ready||S.scale<4||S.mode==='events')return;S.viewportLoadTimer=setTimeout(()=>{const chosen=map();if(!chosen)return;const generation=S.generation,nearby=S.maps.filter(row=>row.name!==S.selected&&included(row)&&visible(row)&&Math.max(row.x,chosen.x)<=Math.min(row.x+row.width,chosen.x+chosen.width)&&Math.max(row.y,chosen.y)<=Math.min(row.y+row.height,chosen.y+chosen.height)).slice(0,4);for(const row of nearby)ensureBuffer(row.name).then(b=>{if(generation===S.generation&&visible(row)&&S.scale>=4){if(!b.raster)rasterize(b);render();}}).catch(()=>{});},250);}
  function screen(x,y){return{x:(x-S.camera.x)*S.scale+S.width/2,y:(y-S.camera.y)*S.scale+S.height/2};}
  function world(clientX,clientY){const r=canvas.getBoundingClientRect();return{x:(clientX-r.left-S.width/2)/S.scale+S.camera.x,y:(clientY-r.top-S.height/2)/S.scale+S.camera.y};}
  function contains(row,p){return p.x>=row.x&&p.y>=row.y&&p.x<row.x+row.width&&p.y<row.y+row.height;}
  function hit(p){const chosen=map();if(chosen&&included(chosen)&&contains(chosen,p))return chosen;return S.maps.filter(row=>included(row)&&contains(row,p)).sort((a,b)=>a.width*a.height-b.width*b.height)[0]||null;}
  function local(row,p){return{x:Math.floor(p.x-row.x),y:Math.floor(p.y-row.y)};}
  function visible(row){const p=screen(row.x,row.y);return p.x+row.width*S.scale>=0&&p.y+row.height*S.scale>=0&&p.x<=S.width&&p.y<=S.height;}
  function render(){if(S.frame!==null)return;S.frame=requestAnimationFrame(()=>{S.frame=null;drawWorld();});}
  function resizeCanvas(){const r=viewport.getBoundingClientRect();S.width=Math.max(1,r.width);S.height=Math.max(1,r.height);S.dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.round(S.width*S.dpr);canvas.height=Math.round(S.height*S.dpr);render();}
  function sprite(id){const info=S.objectById.get(id);if(!info?.preview_url)return null;if(!S.sprites.has(id)){const image=new Image();S.sprites.set(id,image);image.onload=render;image.onerror=()=>S.sprites.set(id,null);image.src=info.preview_url;}const image=S.sprites.get(id);return image?.complete&&image.naturalWidth?image:null;}
  function drawMap(row){
    const p=screen(row.x,row.y),w=row.width*S.scale,h=row.height*S.scale,b=buffer(row.name),image=b?.raster||S.previews.get(row.name);if(image)ctx.drawImage(image,p.x,p.y,w,h);else{ctx.fillStyle=row.archived?'#c5d1b8':'#c0d4a5';ctx.fillRect(p.x,p.y,w,h);}
    if(b&&S.mode==='movement'&&S.scale>=4&&row.name===S.selected){for(let y=0;y<row.height;y++)for(let x=0;x<row.width;x++){const cell=b.data.cells[y*row.width+x],c=(cell>>10)&3,e=(cell>>12)&15;ctx.fillStyle=c?'#b54d416b':'#2b996040';ctx.fillRect(p.x+x*S.scale,p.y+y*S.scale,S.scale,S.scale);if(S.scale>=12){ctx.font=`${Math.min(10,S.scale*.4)}px Consolas,monospace`;ctx.fillStyle='#102f2ee0';ctx.fillRect(p.x+x*S.scale+1,p.y+y*S.scale+S.scale*.27,S.scale-2,S.scale*.5);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(`${c}/${e}`,p.x+(x+.5)*S.scale,p.y+(y+.53)*S.scale);}}}
    if($('#show-grid').checked&&S.scale>=7){ctx.strokeStyle='#25442a38';ctx.lineWidth=.5;ctx.beginPath();for(let x=0;x<=row.width;x++){const px=p.x+x*S.scale;ctx.moveTo(px,p.y);ctx.lineTo(px,p.y+h);}for(let y=0;y<=row.height;y++){const py=p.y+y*S.scale;ctx.moveTo(p.x,py);ctx.lineTo(p.x+w,py);}ctx.stroke();}
    if(b&&S.scale>=3&&($('#show-events').checked||S.mode==='events')){
      const keys=S.mode==='events'&&row.name===S.selected?eventKinds:['object_events'];
      keys.forEach(kind=>b.data.map[kind].forEach((event,index)=>{const ex=row.x+Number(event.x),ey=row.y+Number(event.y),ep=screen(ex,ey);if(ep.x+S.scale<0||ep.y+S.scale<0||ep.x>S.width||ep.y>S.height)return;
        if(kind==='object_events'){const image=sprite(event.graphics_id);if(image){const sw=image.naturalWidth/16*S.scale,sh=image.naturalHeight/16*S.scale;ctx.drawImage(image,ep.x+S.scale/2-sw/2,ep.y+S.scale-sh,sw,sh);}else{ctx.fillStyle='#557e50bb';ctx.fillRect(ep.x+S.scale*.2,ep.y+S.scale*.2,S.scale*.6,S.scale*.7);}}
        if(S.mode==='events'&&row.name===S.selected){ctx.fillStyle=eventColors[kind]+'c9';ctx.fillRect(ep.x+S.scale*.55,ep.y+S.scale*.55,S.scale*.45,S.scale*.45);if(S.scale>=12){ctx.font=`bold ${Math.min(10,S.scale*.32)}px Consolas,monospace`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#fff';ctx.fillText(eventLetters[kind],ep.x+S.scale*.78,ep.y+S.scale*.79);}}
        if(S.event?.name===row.name&&S.event.kind===kind&&S.event.index===index){ctx.strokeStyle='#fff9b5';ctx.lineWidth=2;ctx.strokeRect(ep.x+1,ep.y+1,S.scale-2,S.scale-2);ctx.strokeStyle='#285438';ctx.lineWidth=1;ctx.strokeRect(ep.x-1,ep.y-1,S.scale+2,S.scale+2);}
      }));
    }
    if($('#show-bounds').checked||row.name===S.selected||b?.dirty){ctx.strokeStyle=row.name===S.selected?'#f8f3bd':b?.dirty?'#c4a349':'#426b444f';ctx.lineWidth=row.name===S.selected?2:1;ctx.strokeRect(p.x+.5,p.y+.5,w-1,h-1);if(row.name===S.selected){ctx.strokeStyle='#356642';ctx.lineWidth=1;ctx.strokeRect(p.x-1,p.y-1,w+2,h+2);}}
  }
  function drawWorld(){
    ctx.setTransform(S.dpr,0,0,S.dpr,0,0);ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,S.width,S.height);ctx.fillStyle='#dce8d0';ctx.fillRect(0,0,S.width,S.height);
    const gap=32,origin=screen(0,0);ctx.fillStyle='#bbcdae';for(let x=((origin.x%gap)+gap)%gap;x<S.width;x+=gap)for(let y=((origin.y%gap)+gap)%gap;y<S.height;y+=gap)ctx.fillRect(x,y,1,1);
    drawAreaRegions(false);
    const shown=S.maps.filter(row=>included(row)&&visible(row)),selected=map();shown.filter(row=>row.name!==S.selected).forEach(drawMap);if(selected&&included(selected)&&visible(selected))drawMap(selected);
    if($('#show-labels').checked){const labels=drawAreaRegions(true);ctx.font='10px "Segoe UI",Arial,sans-serif';ctx.textBaseline='top';ctx.textAlign='left';const ordered=shown.filter(row=>row.name!==S.selected);if(selected&&included(selected)&&visible(selected))ordered.push(selected);ordered.forEach(row=>{const p=screen(row.x,row.y);if(row.name!==S.selected&&(row.width*S.scale<60||row.height*S.scale<32))return;const name=mapTitle(row,row.name===S.selected),width=Math.min(250,ctx.measureText(name).width+14),box={x:p.x+3,y:p.y+3,w:width,h:19};if(row.name!==S.selected&&labels.some(other=>box.x<other.x+other.w&&box.x+box.w>other.x&&box.y<other.y+other.h&&box.y+box.h>other.y))return;labels.push(box);ctx.fillStyle=row.name===S.selected?'#f6ffdfed':'#f0f8e1cf';ctx.fillRect(box.x,box.y,width,19);ctx.fillStyle=row.name===S.selected?'#38623a':'#739158';ctx.fillText(name,p.x+10,p.y+7,236);});}
    if(S.drag?.rectangle){const a=S.drag.start,b=S.drag.last,p=screen(Math.min(a.x,b.x),Math.min(a.y,b.y));ctx.fillStyle='#f7f0a64d';ctx.fillRect(p.x,p.y,(Math.abs(a.x-b.x)+1)*S.scale,(Math.abs(a.y-b.y)+1)*S.scale);ctx.strokeStyle='#fff8b7';ctx.lineWidth=1;ctx.strokeRect(p.x,p.y,(Math.abs(a.x-b.x)+1)*S.scale,(Math.abs(a.y-b.y)+1)*S.scale);}
    if(S.hover&&S.scale>=4){const row=hit(S.hover);if(row){const p=screen(Math.floor(S.hover.x),Math.floor(S.hover.y));ctx.strokeStyle='#ffffe4';ctx.lineWidth=1.5;ctx.strokeRect(p.x+.5,p.y+.5,S.scale-1,S.scale-1);}}
    $('#zoom-value').textContent=`${Math.round(S.scale/16*100)}%`;drawMinimap();
  }
  function drawAreaRegions(labelsOnly){const labels=[],sections=S.catalog?.sections||[],groups=S.catalog?.groups||[];ctx.textAlign='left';ctx.textBaseline='top';for(const section of sections){const rows=(section.names||[]).map(name=>map(name)).filter(row=>row&&included(row));if(!rows.length)continue;const b=section.bounds,p=screen(b.x,b.y),w=b.width*S.scale,h=b.height*S.scale;if(p.x+w<0||p.y+h<0||p.x>S.width||p.y>S.height)continue;const color=categories.find(category=>category.id===section.kind)?.color||'#8ea978';if(!labelsOnly){ctx.fillStyle=color+'0c';ctx.fillRect(p.x-5,p.y-5,w+10,h+10);ctx.strokeStyle=color+'38';ctx.lineWidth=1;ctx.strokeRect(p.x-5,p.y-5,w+10,h+10);}else if(w>90&&h>28){const title=`${section.label||'World surface'} · ${rows.length} maps`;ctx.font='11px "Segoe UI",Arial,sans-serif';const tw=Math.min(270,ctx.measureText(title).width+12),box={x:p.x-3,y:p.y-24,w:tw,h:19};ctx.fillStyle='#f3f9e8ee';ctx.fillRect(box.x,box.y,box.w,box.h);ctx.fillStyle=color;ctx.fillText(title,box.x+6,box.y+4,258);labels.push(box);}}
    for(const group of groups){if(!(group.names||[]).some(name=>map(name)&&included(map(name))))continue;const b=group.bounds,p=screen(b.x,b.y),w=b.width*S.scale,h=b.height*S.scale;if(p.x+w<0||p.y+h<0||p.x>S.width||p.y>S.height)continue;if(!labelsOnly&&w>45&&h>25){ctx.strokeStyle='#708c582c';ctx.lineWidth=1;ctx.setLineDash([3,4]);ctx.strokeRect(p.x-3,p.y-3,w+6,h+6);ctx.setLineDash([]);}else if(labelsOnly&&w>85&&h>35){ctx.font='10px "Segoe UI",Arial,sans-serif';const width=Math.min(220,ctx.measureText(group.name).width+10),box={x:p.x,y:p.y-18,w:width,h:16};if(labels.some(other=>box.x<other.x+other.w&&box.x+box.w>other.x&&box.y<other.y+other.h&&box.y+box.h>other.y))continue;labels.push(box);ctx.fillStyle='#edf5e0df';ctx.fillRect(box.x,box.y,box.w,box.h);ctx.fillStyle='#829769';ctx.fillText(group.name,box.x+5,box.y+3,210);}}
    return labels;}
  function fitBounds(bounds){if(!bounds)return;S.camera={x:bounds.x+bounds.width/2,y:bounds.y+bounds.height/2};S.scale=Math.max(.025,Math.min(32,Math.min((S.width-72)/bounds.width,(S.height-90)/bounds.height)));render();scheduleNearbyBuffers();}
  function fitWorld(){S.category='all';$('#category-filter').value='all';renderPlaces();fitBounds(S.catalog?.bounds);}
  function fitCategory(){fitBounds(boundsOf(S.maps.filter(included)));}
  function fitSelection(){const row=map();if(row){if(!included(row)){S.category=categoryOf(row);$('#category-filter').value=S.category;renderPlaces();}fitBounds({x:row.x,y:row.y,width:row.width,height:row.height});}}
  function zoom(multiplier,point){if(!S.catalog)return;const anchor=point||{x:S.width/2,y:S.height/2},before={x:(anchor.x-S.width/2)/S.scale+S.camera.x,y:(anchor.y-S.height/2)/S.scale+S.camera.y};S.scale=Math.max(.025,Math.min(48,S.scale*multiplier));S.camera.x=before.x-(anchor.x-S.width/2)/S.scale;S.camera.y=before.y-(anchor.y-S.height/2)/S.scale;render();scheduleNearbyBuffers();}
  function drawMinimap(){if(!S.catalog)return;const mini=$('#minimap'),c=mini.getContext('2d'),bounds=S.catalog.bounds,pad=7,s=Math.min((mini.width-pad*2)/bounds.width,(mini.height-pad*2)/bounds.height),ox=(mini.width-bounds.width*s)/2-bounds.x*s,oy=(mini.height-bounds.height*s)/2-bounds.y*s;S.minimap={s,ox,oy};c.clearRect(0,0,mini.width,mini.height);c.fillStyle='#e8f0d9';c.fillRect(0,0,mini.width,mini.height);S.maps.forEach(row=>{c.fillStyle=!included(row)?'#cdd5c5':row.name===S.selected?'#396b45':buffer(row.name)?.dirty?'#b8a55a':categories.find(category=>category.id===categoryOf(row))?.color||'#9db783';c.fillRect(ox+row.x*s,oy+row.y*s,Math.max(1,row.width*s),Math.max(1,row.height*s));});c.strokeStyle='#426a3c';c.lineWidth=1;c.strokeRect(ox+(S.camera.x-S.width/(2*S.scale))*s,oy+(S.camera.y-S.height/(2*S.scale))*s,S.width/S.scale*s,S.height/S.scale*s);}
  function renderPlaces(){
    const query=$('#place-search').value.toLowerCase().replace(/\s/g,''),rows=S.maps.filter(row=>included(row)&&(!query||`${row.name} ${nice(row.name)} ${row.area_name||S.areaByMap.get(row.name)?.name||''} ${row.display_name||''} ${row.role_label||''}`.toLowerCase().replace(/\s/g,'').includes(query))),names=new Set(rows.map(row=>row.name));
    $('#place-count').textContent=`${rows.length} maps`;const frag=document.createDocumentFragment();
    for(const category of categories){if(S.category!=='all'&&S.category!==category.id)continue;const categoryRows=rows.filter(row=>categoryOf(row)===category.id),details=node('details','place-group category-group');details.open=!!query||S.category===category.id||S.openCategories.has(category.id);const summary=node('summary','',category.label);summary.append(node('span','',categoryRows.length));details.append(summary);details.ontoggle=()=>{if(details.open)S.openCategories.add(category.id);else S.openCategories.delete(category.id);};
      const areas=S.areas.filter(area=>area.kind===category.id&&area.maps.some(row=>names.has(row.name)));
      for(const area of areas){const areaRows=area.maps.filter(row=>names.has(row.name)).map(row=>map(row.name)),areaDetails=node('details','area-group');areaDetails.open=!!query||S.openAreas.has(area.id);const areaSummary=node('summary','');areaSummary.append(node('span','area-name',area.name),node('span','area-count',areaRows.length));areaDetails.append(areaSummary);areaDetails.ontoggle=()=>{if(areaDetails.open)S.openAreas.add(area.id);else S.openAreas.delete(area.id);};
        const areaFocus=node('button','area-focus','Show this whole area');areaFocus.type='button';areaFocus.onclick=()=>{fitBounds(boundsOf(areaRows));};areaDetails.append(areaFocus);let role='';for(const row of areaRows){const roleLabel=row.role_label||area.maps.find(item=>item.name===row.name)?.role_label||'Locations';if(roleLabel!==role){role=roleLabel;areaDetails.append(node('div','role-label',roleLabel));}const button=node('button',`place-row${row.name===S.selected?' active':''}`);button.type='button';button.setAttribute('aria-label',`${mapTitle(row)} · ${roleLabel}`);button.title=mapTitle(row);button.innerHTML=`<span class="place-icon">${row.is_outdoor?'⌁':row.role==='homes'?'⌂':row.role==='gyms'?'◈':'▧'}</span><div><strong>${esc(mapTitle(row,false))}</strong><small>${row.width} × ${row.height} tiles${row.archived?' · archived':''}${row.overlaps?.length?' · overlapping layer':''}</small></div>${buffer(row.name)?.dirty?'<span class="dirty-dot"></span>':''}`;button.onclick=async()=>{await selectMap(row.name);fitSelection();};areaDetails.append(button);}details.append(areaDetails);}
      if(!categoryRows.length)details.append(node('p','empty','No matching maps in this category.'));frag.append(details);
    }
    $('#place-list').replaceChildren(frag);
  }
  async function setCategory(category){if(!S.ready)return;S.category=category;$('#category-filter').value=category;const selected=map();if(selected&&!included(selected)){const next=S.maps.find(included);if(next)await selectMap(next.name);}renderPlaces();fitCategory();render();}
  async function selectMap(name){
    if(!map(name))return;const request=++S.selectionRequest;S.selected=name;S.event=null;window.WorldTools?.selection(name);const row=map(name),area=S.areaByMap.get(name);if(S.ready||new URLSearchParams(location.search).get('map')){S.openCategories.add(categoryOf(row));if(area)S.openAreas.add(area.id);}$('#selected-name').textContent=mapTitle(row);$('#selected-detail').textContent=`${row.role_label||'Map'} · ${row.width} × ${row.height} tiles · loading editable tiles…`;$('#context-name').textContent=mapTitle(row);$('#map-context').hidden=false;$('#selected-links').hidden=false;$('#area-link').href=`/areas?map=${encodeURIComponent(name)}`;$('#connection-link').href=`/connections?map=${encodeURIComponent(name)}`;$('#story-link').href=`/campaign?map=${encodeURIComponent(name)}`;renderPlaces();render();
    try{const b=await ensureBuffer(name);if(request!==S.selectionRequest)return;if(!b.valid.has(S.tile))S.tile=[...b.valid][0]||0;if(!b.raster)rasterize(b);$('#selected-detail').textContent=`${row.role_label||'Map'} · ${row.width} × ${row.height} tiles${row.is_outdoor===false?' · Interior / separate layer, editable on this same canvas':''}${row.overlaps?.length?' · overlaps '+row.overlaps.map(nice).join(', ')+'; choose the desired map in the sidebar':''}`;renderPalette();renderTileSelection();renderEvents();$('#set-eraser').disabled=false;scheduleNearbyBuffers();pruneRasters();status();render();}
    catch(err){error(err.message);toast(err.message,true);}
  }
  function pruneRasters(){const rasters=[...S.buffers].filter(([name,b])=>b.raster&&name!==S.selected&&!b.dirty&&!visible(map(name)));if(rasters.length>8)for(const[name,b]of rasters.slice(0,rasters.length-8))b.raster=null;}
  function setPanel(panel){S.panel=panel;$$('[data-panel]').forEach(button=>{button.classList.toggle('active',button.dataset.panel===panel);button.setAttribute('aria-selected',String(button.dataset.panel===panel));});['tiles','objects','events'].forEach(name=>$(`#panel-${name}`).hidden=name!==panel);}
  function setMode(mode){if(!S.ready)return;S.mode=mode;S.place=false;$$('[data-mode]').forEach(button=>button.classList.toggle('active',button.dataset.mode===mode));$('#movement-options').hidden=mode!=='movement';$('#event-toolbar').hidden=mode!=='events';if(mode==='events')setPanel('events');else setPanel('tiles');syncPlace();render();}
  function setTool(tool){if(!S.ready)return;S.tool=tool;$$('[data-tool]').forEach(button=>button.classList.toggle('active',button.dataset.tool===tool));if(tool!=='select'&&S.mode==='events')setMode('terrain');if(tool!=='select'&&S.scale<3)fitSelection();render();}
  function renderPalette(){const b=buffer();if(!b){$('#tile-palette').replaceChildren(node('p','empty','Choose a place to see its tiles.'));return;}const query=$('#tile-search').value.toLowerCase().trim(),bank=$('#tile-bank').value,used=new Set(b.data.cells.map(value=>value&1023));const tiles=b.data.tileset.metatiles.filter(t=>t.valid!==false&&(bank==='all'||bank==='primary'&&t.id<512||bank==='secondary'&&t.id>=512||bank==='used'&&used.has(t.id))&&(!query||`${t.id} 0x${t.id.toString(16)} ${t.behavior_name||''}`.toLowerCase().includes(query)));$('#tile-count').textContent=`${tiles.length} tiles`;$('#tileset-name').textContent=b.data.layout.secondary_tileset.replace('gTileset_','');const frag=document.createDocumentFragment();tiles.forEach(tile=>{const button=node('button',`tile-button${tile.id===S.tile?' active':''}`);button.dataset.tile=tile.id;button.type='button';button.title=`Tile ${tile.id} · ${tile.behavior_name||'behavior '+tile.behavior}`;button.setAttribute('aria-label',button.title);const c=node('canvas');c.width=16;c.height=16;drawTile(c.getContext('2d'),b,tile.id,0,0);button.append(c,node('span','',tile.id));button.onclick=()=>{S.tile=tile.id;setMode('terrain');setTool('brush');renderTileSelection();};frag.append(button);});$('#tile-palette').replaceChildren(frag);}
  function renderTileSelection(){const b=buffer();if(!b)return;const meta=b.data.tileset.metatiles.find(t=>t.id===S.tile);$('#tile-title').textContent=`Tile ${S.tile} · ${S.tile<512?'shared':'local'}`;$('#tile-behavior').textContent=meta?.behavior_name||`Behavior ${meta?.behavior??'?'}`;const eraser=S.erasers.get(S.selected)||0;for(const [id,tile] of [['tile-preview',S.tile],['eraser-preview',eraser]]){const c=$(`#${id}`),context=c.getContext('2d');context.clearRect(0,0,16,16);drawTile(context,b,tile,0,0);}$('#eraser-label').textContent=`Eraser: tile ${eraser}. Select a tile, then “Use as eraser” to change it.`;$$('.tile-button').forEach(button=>button.classList.toggle('active',Number(button.dataset.tile)===S.tile));}
  function brushState(){const b=buffer();return{mode:S.mode,tool:S.tool,tile:S.tool==='erase'?(S.erasers.get(S.selected)||0):S.tile,primary:b?.data.layout.primary_tileset,secondary:b?.data.layout.secondary_tileset,preserve:$('#preserve-movement').checked,collision:Number($('#collision').value)&3,elevation:Math.max(0,Math.min(15,Number($('#elevation').value)||0)),paintCollision:$('#paint-collision').checked,paintElevation:$('#paint-elevation').checked};}
  function compatible(b,brush){return brush.mode==='movement'||b.valid.has(brush.tile)&&(brush.tile<512?b.data.layout.primary_tileset===brush.primary:b.data.layout.secondary_tileset===brush.secondary&&b.data.layout.primary_tileset===brush.primary);}
  function paintValue(cell,brush){if(brush.mode==='movement'){if(brush.paintCollision)cell=(cell&~0xc00)|(brush.collision<<10);if(brush.paintElevation)cell=(cell&~0xf000)|(brush.elevation<<12);return cell;}return brush.preserve?(cell&0xfc00)|brush.tile:brush.tile|(brush.collision<<10)|(brush.elevation<<12);}
  function touch(stroke,name){if(!stroke.before.has(name))stroke.before.set(name,snapshot(buffer(name)));}
  function paintCell(stroke,name,x,y){const b=buffer(name);if(!b)return;if(!compatible(b,stroke.brush)){if(!stroke.warned){toast('This neighboring place uses different artwork. Select it and choose its tiles before painting there.');stroke.warned=true;}return;}if(x<0||y<0||x>=b.data.width||y>=b.data.height)return;const i=y*b.data.width+x,value=paintValue(b.data.cells[i],stroke.brush);if(value===b.data.cells[i])return;touch(stroke,name);b.data.cells[i]=value;if(!b.raster)rasterize(b);else updateTileRaster(b,i);}
  function paintWorld(stroke,p){const row=hit({x:p.x+.5,y:p.y+.5});if(!row)return;const x=Math.floor(p.x-row.x),y=Math.floor(p.y-row.y);if(buffer(row.name))paintCell(stroke,row.name,x,y);else{stroke.pending.push({name:row.name,x,y});if(!stroke.loads.has(row.name))stroke.loads.set(row.name,ensureBuffer(row.name));}}
  function worldLine(stroke,a,b){let x=a.x,y=a.y;const dx=Math.abs(b.x-a.x),dy=-Math.abs(b.y-a.y),sx=a.x<b.x?1:-1,sy=a.y<b.y?1:-1;let err=dx+dy,count=0;while(count++<2000){paintWorld(stroke,{x,y});if(x===b.x&&y===b.y)break;const doubled=err*2;if(doubled>=dy){err+=dy;x+=sx;}if(doubled<=dx){err+=dx;y+=sy;}}}
  function flood(stroke,row,p){const b=buffer(row.name),start=p.y*b.data.width+p.x,mask=stroke.brush.mode==='terrain'?1023:(stroke.brush.paintCollision?0xc00:0)|(stroke.brush.paintElevation?0xf000:0);if(!mask||!compatible(b,stroke.brush))return;const source=b.data.cells[start];if((paintValue(source,stroke.brush)&mask)===(source&mask))return;touch(stroke,row.name);const queue=[start],seen=new Uint8Array(b.data.cells.length);seen[start]=1;while(queue.length){const i=queue.pop();if((b.data.cells[i]&mask)!==(source&mask))continue;b.data.cells[i]=paintValue(b.data.cells[i],stroke.brush);const x=i%b.data.width,y=Math.floor(i/b.data.width),next=[];if(x>0)next.push(i-1);if(x<b.data.width-1)next.push(i+1);if(y>0)next.push(i-b.data.width);if(y<b.data.height-1)next.push(i+b.data.width);for(const n of next)if(!seen[n]){seen[n]=1;queue.push(n);}}rasterize(b);}
  function commit(before){const changed=new Map();for(const [name,value]of before){const b=buffer(name);if(JSON.stringify(value)!==fingerprint(b)){changed.set(name,value);updateDirty(b);}}if(changed.size){S.history.push(changed);if(S.history.length>50)S.history.shift();S.future=[];}status();renderPlaces();render();}
  function mutate(name,callback){if(S.busy||S.finishing)return;const b=buffer(name);if(!b)return;const before=new Map([[name,snapshot(b)]]);callback(b);commit(before);renderEvents();}
  function restoreSnapshot(b,value){Object.assign(b.data,clone(value));updateDirty(b);rasterize(b);}
  function undo(redo=false){const from=redo?S.future:S.history,to=redo?S.history:S.future;if(!from.length||S.busy||S.finishing)return;const entry=from.pop(),inverse=new Map();for(const[name,value]of entry){const b=buffer(name);inverse.set(name,snapshot(b));restoreSnapshot(b,value);}to.push(inverse);S.event=null;status();renderPlaces();renderEvents();render();}
  function pointInfo(p){S.hover=p;const row=hit(p);if(row){const pt=local(row,p),b=buffer(row.name),cell=b?.data.cells[pt.y*row.width+pt.x];$('#cursor').textContent=`${nice(row.name)} · X ${pt.x}, Y ${pt.y}${cell!==undefined?` · tile ${cell&1023} · collision ${(cell>>10)&3} / elevation ${(cell>>12)&15}`:''}`;}else $('#cursor').textContent=`World X ${Math.floor(p.x)}, Y ${Math.floor(p.y)} · drag to explore`;render();}
  async function pickAt(p){const row=hit(p);if(!row)return;if(S.selected!==row.name)await selectMap(row.name);const b=await ensureBuffer(row.name),pt=local(row,p),cell=b.data.cells[pt.y*row.width+pt.x];S.tile=cell&1023;$('#collision').value=(cell>>10)&3;$('#elevation').value=(cell>>12)&15;renderPalette();renderTileSelection();setPanel('tiles');toast(`Picked tile ${S.tile} from ${nice(row.name)}.`);}
  function eventAt(row,p){const b=buffer(row.name);if(!b)return null;const pt=local(row,p),hits=[];eventKinds.forEach(kind=>b.data.map[kind].forEach((event,index)=>{if(Number(event.x)===pt.x&&Number(event.y)===pt.y)hits.push({name:row.name,kind,index});}));if(!hits.length)return null;const chosen=hits.findIndex(event=>event.name===S.event?.name&&event.kind===S.event.kind&&event.index===S.event.index);return hits[(chosen+1)%hits.length];}
  function chosenEvent(){return S.event?buffer(S.event.name)?.data.map[S.event.kind]?.[S.event.index]:null;}
  canvas.onpointerdown=async event=>{
    if(!S.ready||S.busy||S.finishing)return;const press=++S.press;S.pointerActive=event.pointerId;const p=world(event.clientX,event.clientY),row=hit(p),initialBrush=brushState();event.preventDefault();canvas.setPointerCapture(event.pointerId);
    if(event.button===1||S.space||!row&&event.button===0){S.drag={pan:true,clientX:event.clientX,clientY:event.clientY,camera:{...S.camera}};viewport.classList.add('panning');return;}
    if(event.button===2||S.tool==='picker'&&S.mode!=='events'){await pickAt(p);return;}if(event.button!==0||!row)return;
    if(S.tool==='select'&&S.mode!=='events'){await selectMap(row.name);return;}
    if(!buffer(row.name)||S.selected!==row.name){const previous=S.selected;await selectMap(row.name);if(!buffer(row.name))return;if(!buffer(previous)||S.tool==='select'&&S.mode!=='events')return;if(S.mode!=='events'&&!compatible(buffer(row.name),initialBrush)){toast('This place uses different landscape artwork. Choose a tile from its palette to paint here.');return;}}
    if(S.pointerActive!==event.pointerId||S.press!==press)return;
    if(S.scale<3){fitSelection();toast('Zoomed in for tile editing. Click again to paint.');return;}
    if(S.mode==='events'){if(S.place){addEvent(row,local(row,p));return;}S.event=eventAt(row,p);setPanel('events');renderEvents();render();if(S.event)S.drag={event:true,name:row.name,before:new Map([[row.name,snapshot(buffer(row.name))]]),pointer:event.pointerId};return;}
    const tile={x:Math.floor(p.x),y:Math.floor(p.y)},stroke={brush:initialBrush,name:row.name,start:tile,last:tile,before:new Map(),pending:[],loads:new Map(),rectangle:S.tool==='rectangle'};S.drag=stroke;
    if(S.tool==='fill'){flood(stroke,row,local(row,p));await finishStroke();}else if(!stroke.rectangle)paintWorld(stroke,tile);render();
  };
  canvas.onpointermove=event=>{const p=world(event.clientX,event.clientY);pointInfo(p);if(!S.drag)return;const drag=S.drag;if(drag.pan){S.camera.x=drag.camera.x-(event.clientX-drag.clientX)/S.scale;S.camera.y=drag.camera.y-(event.clientY-drag.clientY)/S.scale;render();return;}if(drag.event){const row=map(drag.name),chosen=chosenEvent();if(chosen){chosen.x=Math.max(0,Math.min(row.width-1,Math.floor(p.x-row.x)));chosen.y=Math.max(0,Math.min(row.height-1,Math.floor(p.y-row.y)));render();}return;}const tile={x:Math.floor(p.x),y:Math.floor(p.y)};if(drag.rectangle){const row=map(drag.name);tile.x=Math.max(row.x,Math.min(row.x+row.width-1,tile.x));tile.y=Math.max(row.y,Math.min(row.y+row.height-1,tile.y));}else worldLine(drag,drag.last,tile);drag.last=tile;render();};
  async function finishStroke(){if(!S.drag)return;const stroke=S.drag;S.drag=null;viewport.classList.remove('panning');if(stroke.pan){scheduleNearbyBuffers();return;}if(stroke.event){commit(stroke.before);renderEvents();return;}if(stroke.rectangle)for(let y=Math.min(stroke.start.y,stroke.last.y);y<=Math.max(stroke.start.y,stroke.last.y);y++)for(let x=Math.min(stroke.start.x,stroke.last.x);x<=Math.max(stroke.start.x,stroke.last.x);x++)paintWorld(stroke,{x,y});
    if(stroke.loads.size){S.finishing=true;status();const results=await Promise.allSettled(stroke.loads.values());for(const result of results)if(result.status==='rejected')toast(result.reason.message,true);for(const pending of stroke.pending)paintCell(stroke,pending.name,pending.x,pending.y);S.finishing=false;}
    commit(stroke.before);if($('#tile-bank').value==='used')renderPalette();}
  function releasePointer(){S.pointerActive=null;finishStroke();}
  canvas.onpointerup=releasePointer;canvas.onpointercancel=releasePointer;canvas.onlostpointercapture=releasePointer;canvas.onpointerleave=()=>{if(!S.drag){S.hover=null;render();}};canvas.oncontextmenu=e=>e.preventDefault();
  viewport.addEventListener('wheel',event=>{event.preventDefault();if(!S.ready)return;const r=canvas.getBoundingClientRect();zoom(Math.exp(-Math.max(-100,Math.min(100,event.deltaY))*.004),{x:event.clientX-r.left,y:event.clientY-r.top});},{passive:false});
  function renderObjects(){const query=$('#object-search').value.toLowerCase(),objects=S.objects.filter(object=>`${object.name} ${object.id}`.toLowerCase().includes(query));$('#object-count').textContent=`${objects.length} people & objects`;const frag=document.createDocumentFragment();for(const object of objects){const button=node('button',`object-card${object.id===S.object?' active':''}`);button.type='button';button.title=object.id;if(object.preview_url){const img=node('img');img.src=object.preview_url;img.alt='';img.loading='lazy';button.append(img);}button.append(node('span','',nice(object.name||object.id).toLowerCase()));button.onclick=()=>{if(!S.ready||!buffer())return;S.object=object.id;setMode('events');S.place=true;$('#event-type').value='object_events';syncPlace();setPanel('objects');renderObjects();if(S.scale<4)fitSelection();toast(`Click the world to place ${nice(object.name||object.id).toLowerCase()}.`);};frag.append(button);}$('#object-palette').replaceChildren(frag);}
  function syncPlace(){$('#place-event').classList.toggle('selected',S.place);$('#select-event').classList.toggle('selected',!S.place);$('#event-mode-hint').textContent=S.place?'Click on the world to place the selected event.':'Click a person or marker to select. Drag to move.';}
  function addEvent(row,p){const kind=$('#event-type').value;let event={x:p.x,y:p.y,elevation:3};if(kind==='object_events')Object.assign(event,{graphics_id:S.object,movement_type:'MOVEMENT_TYPE_FACE_DOWN',movement_range_x:0,movement_range_y:0,trainer_type:'TRAINER_TYPE_NONE',trainer_sight_or_berry_tree_id:'0',script:'0x0',flag:'0'});else if(kind==='warp_events')Object.assign(event,{elevation:0,dest_map:buffer(row.name).data.map.id,dest_warp_id:'0'});else if(kind==='coord_events')Object.assign(event,{type:'trigger',var:'VAR_TEMP_0',var_value:'0',script:'0x0'});else Object.assign(event,{type:'sign',elevation:0,player_facing_dir:'BG_EVENT_PLAYER_FACING_ANY',script:'0x0'});mutate(row.name,b=>{b.data.map[kind].push(event);S.event={name:row.name,kind,index:b.data.map[kind].length-1};});S.place=false;syncPlace();setPanel('events');renderEvents();if(kind==='warp_events')toast('Doorway marker added. Set its destination or connect it using Connections.');}
  let fieldId=0;
  function field(label,key,value,options={}){const wrap=node('label',`field${options.wide?' wide':''}`,label),input=node('input',options.mono?'mono':'');input.id=`worldmap-field-${++fieldId}`;wrap.htmlFor=input.id;input.setAttribute('aria-label',label);input.type=options.type||'text';input.dataset.key=key;if(options.min!==undefined)input.min=options.min;if(options.max!==undefined)input.max=options.max;if(options.list)input.setAttribute('list',options.list);input.value=value??'';wrap.append(input);return wrap;}
  function eventName(event,kind){return kind==='object_events'?nice(event.graphics_id).toLowerCase():kind==='warp_events'?nice(event.dest_map):event.script||event.type||eventLabels[kind];}
  function renderEvents(){const b=buffer();if(!b)return;const frag=document.createDocumentFragment();let count=0;eventKinds.forEach(kind=>b.data.map[kind].forEach((event,index)=>{count++;const button=node('button',`event-row${S.event?.name===S.selected&&S.event.kind===kind&&S.event.index===index?' active':''}`);button.innerHTML=`<span class="event-tag">${eventLetters[kind]}</span><div><strong>${esc(eventName(event,kind))}</strong><small>${eventLabels[kind]} ${index} · ${event.x}, ${event.y}</small></div>`;button.onclick=()=>{setMode('events');S.event={name:S.selected,kind,index};renderEvents();render();};frag.append(button);}));$('#event-list').replaceChildren(frag);$('#event-count').textContent=count;const host=$('#event-inspector');host.replaceChildren();const event=chosenEvent();if(!event||S.event.name!==S.selected){host.append(node('p','empty','Choose People & events, then click a person or marker on the world.'));return;}const selected=clone(S.event),row=map(),form=node('div','event-form'),heading=node('div','event-form-heading');heading.append(node('strong','',`${eventLabels[selected.kind]} ${selected.index}`));const buttons=node('div'),duplicate=node('button','button tiny','Duplicate'),remove=node('button','button tiny danger','Delete');duplicate.onclick=duplicateEvent;remove.onclick=deleteEvent;buttons.append(duplicate,remove);heading.append(buttons);form.append(heading);const grid=node('div','fields-grid');grid.append(field('X position','x',event.x,{type:'number',min:0,max:row.width-1}),field('Y position','y',event.y,{type:'number',min:0,max:row.height-1}),field('Elevation','elevation',event.elevation,{type:'number',min:0,max:15}));
    if(selected.kind==='object_events'){grid.append(field('Sprite','graphics_id',event.graphics_id,{wide:true,mono:true,list:'object-ids'}),field('Movement','movement_type',event.movement_type,{wide:true,mono:true}),field('Wander X','movement_range_x',event.movement_range_x,{type:'number',min:0,max:15}),field('Wander Y','movement_range_y',event.movement_range_y,{type:'number',min:0,max:15}),field('Script','script',event.script,{wide:true,mono:true}),field('Hide flag','flag',event.flag,{wide:true,mono:true}));}
    else if(selected.kind==='warp_events')grid.append(field('Destination map','dest_map',event.dest_map,{wide:true,mono:true,list:'map-ids'}),field('Destination warp index','dest_warp_id',event.dest_warp_id,{wide:true,mono:true}));
    else{for(const key of ['type','var','var_value','player_facing_dir','script','item','flag','weather','secret_base_id'])if(event[key]!==undefined)grid.append(field(nice(key),key,event[key],{wide:true,mono:true}));}
    $$('input',grid).forEach(input=>input.onchange=()=>{if(!input.reportValidity())return;const value=input.type==='number'?Number(input.value):input.value.trim();mutate(selected.name,b=>{b.data.map[selected.kind][selected.index][input.dataset.key]=value;});});form.append(grid);
    const details=node('details','event-json');details.append(node('summary','','All event properties · JSON'));const textarea=node('textarea');textarea.value=JSON.stringify(event,null,2);textarea.setAttribute('aria-label','All event properties JSON');const apply=node('button','button tiny','Apply event properties');apply.onclick=()=>{try{const value=JSON.parse(textarea.value);if(!value||Array.isArray(value)||typeof value!=='object')throw new Error('Use a JSON object.');if(!Number.isInteger(value.x)||!Number.isInteger(value.y)||value.x<0||value.y<0||value.x>=row.width||value.y>=row.height)throw new Error('Coordinates must be inside this place.');mutate(selected.name,b=>{b.data.map[selected.kind][selected.index]=value;});toast('Event properties applied. Save world to keep them.');}catch(err){toast(err.message,true);}};details.append(textarea,apply);form.append(details);host.append(form);}
  function duplicateEvent(){const selected=S.event,event=chosenEvent();if(!selected||!event)return;mutate(selected.name,b=>{const copy=clone(event);delete copy.local_id;copy.x=Math.min(b.data.width-1,Number(copy.x)+1);b.data.map[selected.kind].push(copy);S.event={name:selected.name,kind:selected.kind,index:b.data.map[selected.kind].length-1};});}
  async function deleteEvent(){const selected=S.event,event=chosenEvent();if(!selected||!event)return;const note=selected.kind==='warp_events'?'Removing this warp shifts later warp indexes. Review incoming doorways that use those indexes.':'Story scripts may refer to this event’s local ID or its position in the event list.';if(!await dialog('Remove this event?',`<p>${esc(eventName(event,selected.kind))}</p><p>${esc(note)} You can undo this change before saving.</p>`,'Delete event'))return;mutate(selected.name,b=>{b.data.map[selected.kind].splice(selected.index,1);S.event=null;});}
  async function saveWorld(){if(!S.ready||S.busy||S.finishing)return;await finishStroke();const dirty=dirtyBuffers();if(!dirty.length)return;const shared=[...new Set(dirty.flatMap(b=>[...(b.data.shared_with||[]),...(b.data.events_shared_with||[])]))];let confirmed=false;if(shared.length){const result=await dialog('Save shared world data?',`<p>${dirty.length} edited place${dirty.length===1?'':'s'} will be saved together.</p><p>Some terrain or events are shared with: ${esc(shared.map(nice).join(', '))}.</p><label><input name="shared" type="checkbox" required>I want to update the shared data in those places too.</label>`,'Save world');if(!result)return;confirmed=true;}S.busy=true;status();error('');
    try{const response=await api('/api/worldmap/save',{maps:dirty.map(b=>({name:b.data.name,revision:b.data.revision,...snapshot(b),confirm_shared:confirmed}))});const freshRecords=response.saved||[];for(const data of freshRecords){const b=buffer(data.name);if(!b)continue;eventKinds.forEach(kind=>data.map[kind]||=[]);b.data=data;b.saved=fingerprint(b);b.dirty=false;rasterize(b);}if(freshRecords.length!==dirty.length){for(const b of dirty)if(b.dirty){const data=await api(`/api/world/map?name=${encodeURIComponent(b.data.name)}`);eventKinds.forEach(kind=>data.map[kind]||=[]);b.data=data;b.saved=fingerprint(b);b.dirty=false;rasterize(b);}}S.history=[];S.future=[];renderPlaces();renderEvents();render();toast(`Saved ${dirty.length} place${dirty.length===1?'':'s'} together with backups.`);}
    catch(err){error(err.message);toast(err.message,true);}finally{S.busy=false;status();}}
  async function reloadWorld(preferred=S.selected,focus=false){
    S.generation++;S.selectionRequest++;clearTimeout(S.viewportLoadTimer);S.previewInFlight.clear();S.previewFailed.clear();const[catalog,areas,allMaps]=await Promise.all([api('/api/worldmap'),api('/api/areas'),api('/api/world/maps')]);S.catalog=catalog;S.maps=catalog.maps;S.byName=new Map(S.maps.map(row=>[row.name,row]));S.areas=areas.areas;S.areaByMap.clear();S.areas.forEach(area=>area.maps.forEach(row=>S.areaByMap.set(row.name,area)));S.buffers.clear();S.loads.clear();S.atlases.clear();S.sprites.clear();S.erasers.clear();S.previews.clear();S.history=[];S.future=[];S.event=null;S.drag=null;S.preloadDone=0;S.previewDone=0;$('#map-ids').replaceChildren(...allMaps.maps.map(row=>{const option=node('option');option.value=row.id;option.label=nice(row.name);return option;}));const next=map(preferred)?preferred:map('LittlerootTown')?'LittlerootTown':S.maps[0]?.name;if(next){if(!included(map(next))){S.category='all';$('#category-filter').value='all';}await selectMap(next);}if(focus)fitSelection();status();render();preload();
  }
  async function requireSavedWorld(){
    if(!dirtyBuffers().length)return true;
    if(!await dialog('Save your world first?','<p>Save your pending terrain and event edits before changing the world’s saved history or adding a new place.</p>','Save world and continue'))return false;
    await saveWorld();return !dirtyBuffers().length;
  }
  async function savedHistory(){
    if(!S.ready||S.busy||S.finishing)return;
    try{const data=await api('/api/transactions'),transactions=data.transactions;if(!transactions.length){await dialog('Your saved world history','<p>World, terrain, and story saves will appear here. Restore a save to bring back its previous source files, including terrain data.</p>','Got it',true);return;}
      const options=transactions.map(transaction=>`<option value="${esc(transaction.id)}">${esc(transaction.label)} · ${transaction.files.length} files</option>`).join('');
      const pending=dialog('Restore a saved edit',`<p>Restore all files changed by one save to their previous versions. Restore newer edits first when they touch the same files.</p><label class="field" for="restore-transaction">Saved edit<select id="restore-transaction" aria-label="Saved edit" name="transaction">${options}</select></label><div id="restore-files" class="restore-files"></div><p>Restoring a “New blank map” save removes that new place. Restoring an “Undo” save reapplies its changes.</p>`,'Restore previous files');
      const showFiles=()=>{const transaction=transactions.find(t=>t.id===$('#restore-transaction').value);$('#restore-files').replaceChildren(...transaction.files.map(file=>node('div','',file)));};$('#restore-transaction').onchange=showFiles;showFiles();const values=await pending;if(!values)return;
      if(!await requireSavedWorld())return;S.busy=true;status();error('');await api('/api/transaction/undo',{id:values.transaction});await reloadWorld();toast('Previous source files restored. The world now shows the restored version.');
    }catch(err){error(err.message);toast(err.message,true);}finally{S.busy=false;status();}
  }
  async function newPlace(){
    if(!S.ready||S.busy||S.finishing)return;
    const templates=S.maps.filter(row=>!row.archived&&['MAP_TYPE_TOWN','MAP_TYPE_CITY','MAP_TYPE_ROUTE','MAP_TYPE_OCEAN_ROUTE'].includes(row.map_type));
    const selectedTemplate=templates.some(row=>row.name===S.selected)?S.selected:templates.some(row=>row.name==='LittlerootTown')?'LittlerootTown':templates[0]?.name;
    const options=templates.map(row=>`<option value="${esc(row.name)}"${row.name===selectedTemplate?' selected':''}>${esc(nice(row.name))}</option>`).join('');
    const values=await dialog('Add a blank place to your world',`<p>Create a new town, route, or outdoor area with its own blank terrain. Its outdoor template supplies the artwork and map settings.</p><div class="fields-grid"><label class="field wide" for="blank-name">Place name<input id="blank-name" name="name" aria-label="Place name" placeholder="MyNewTown" pattern="[A-Z][A-Za-z0-9_]{0,63}" maxlength="64" required></label><label class="field wide" for="blank-template">Outdoor template<select id="blank-template" name="template" aria-label="Outdoor template">${options}</select></label><label class="field" for="blank-width">Width<input id="blank-width" name="width" aria-label="Width" type="number" min="1" max="255" value="30" required></label><label class="field" for="blank-height">Height<input id="blank-height" name="height" aria-label="Height" type="number" min="1" max="255" value="30" required></label></div><p>The new place appears as a detached area until you connect it using walking edges or doorways. Creating it saves its initial source files.</p>`,'Create blank place');
    if(!values)return;const width=Number(values.width),height=Number(values.height);if((width+15)*(height+14)>10240){toast('This size exceeds Emerald’s map buffer. Use smaller dimensions.',true);return;}if(!await requireSavedWorld())return;S.busy=true;status();error('');
    try{await api('/api/world/new',{name:values.name,template:values.template,width,height,blank:true});await reloadWorld(values.name,true);history.replaceState(null,'',`/worldmap?map=${encodeURIComponent(values.name)}`);toast(`${nice(values.name)} is ready. Paint it directly on the world.`);}
    catch(err){error(err.message);toast(err.message,true);}finally{S.busy=false;status();}
  }
  $('#save-world').onclick=saveWorld;$('#undo').onclick=()=>undo();$('#redo').onclick=()=>undo(true);$('#fit-world').onclick=fitWorld;$('#fit-selection').onclick=fitSelection;$('#zoom-value').onclick=fitWorld;$('#zoom-in').onclick=()=>zoom(1.3);$('#zoom-out').onclick=()=>zoom(1/1.3);$('#place-search').oninput=renderPlaces;
  $('#saved-history').onclick=savedHistory;$('#new-place').onclick=newPlace;$('#category-filter').onchange=event=>setCategory(event.target.value);$('#fit-category').onclick=fitCategory;
  $$('[data-tool]').forEach(button=>button.onclick=()=>setTool(button.dataset.tool));$$('[data-mode]').forEach(button=>button.onclick=()=>setMode(button.dataset.mode));$$('[data-panel]').forEach(button=>button.onclick=()=>setPanel(button.dataset.panel));['show-labels','show-bounds','show-grid','show-events'].forEach(id=>$(`#${id}`).onchange=render);
  $('#tile-bank').onchange=renderPalette;$('#tile-search').oninput=renderPalette;$('#set-eraser').onclick=()=>{if(buffer()){S.erasers.set(S.selected,S.tile);renderTileSelection();toast(`Eraser now uses tile ${S.tile} in ${nice(S.selected)}.`);}};$('#object-search').oninput=renderObjects;
  $('#place-event').onclick=()=>{S.place=true;syncPlace();if(S.scale<3)fitSelection();};$('#select-event').onclick=()=>{S.place=false;syncPlace();};
  $('#minimap').onclick=event=>{if(!S.minimap)return;const r=event.currentTarget.getBoundingClientRect(),x=(event.clientX-r.left)/r.width*event.currentTarget.width,y=(event.clientY-r.top)/r.height*event.currentTarget.height;S.camera.x=(x-S.minimap.ox)/S.minimap.s;S.camera.y=(y-S.minimap.oy)/S.minimap.s;render();};
  $('#help').onclick=()=>dialog('Build directly on the whole world',`<ul class="tips"><li>Every place on this canvas uses its actual terrain. <strong>Click a place, choose a tile, and paint here.</strong> You stay on the world canvas.</li><li>Scroll to zoom. Hold Space and drag, middle-drag, or drag empty space to explore. The small navigator moves your view around the world.</li><li>Paint, erase, fill, and rectangles edit the source map tiles. A paint stroke continues into neighboring maps when they use compatible artwork.</li><li>People &amp; events lets you add, select, move, duplicate, and delete people, objects, doorways, and story triggers on this same canvas.</li><li>Movement edits collision and elevation. Landscape tile behavior also affects where the player can walk.</li><li>Save world writes every edited place together with backups. Ctrl Z and Ctrl Shift Z undo and redo pending edits.</li><li>Every home, building floor, cave, underwater area, and special map is here. Open the four area categories or search by area, room, or floor. Interiors and detached areas are grouped around the connected world surface; this arrangement does not create walking connections.</li><li>Some original walking connections form inconsistent loops. ${S.catalog?.conflicts?.length||0} seams and ${S.catalog?.overlaps?.length||0} overlap areas are flagged by the source layout. At an overlap, choose the desired place in the sidebar; that place is displayed and edited on top.</li><li>The PokéNav region picture is a separate game screen. This canvas edits the playable world’s actual terrain.</li><li>Saving edits source files. Building and playtesting a playable ROM still uses the separate build setup.</li></ul>${(S.catalog?.warnings||[]).map(w=>`<p>${esc(w)}</p>`).join('')}`,'Got it',true);
  document.addEventListener('keydown',event=>{if($('#dialog').open)return;const typing=/INPUT|TEXTAREA|SELECT/.test(event.target.tagName)||event.target.isContentEditable;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();document.activeElement?.blur();saveWorld();return;}if(typing)return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();undo(event.shiftKey);return;}if(event.code==='Space'){event.preventDefault();S.space=true;return;}if(event.key==='Escape'){S.place=false;S.event=null;syncPlace();renderEvents();render();return;}if(event.key==='Delete'&&S.event){event.preventDefault();deleteEvent();return;}const tool={v:'select',b:'brush',e:'erase',f:'fill',r:'rectangle',i:'picker'}[event.key.toLowerCase()];if(tool&&!event.ctrlKey&&!event.metaKey)setTool(tool);});
  document.addEventListener('keyup',event=>{if(event.code==='Space')S.space=false;});window.addEventListener('blur',()=>{S.space=false;finishStroke();});window.addEventListener('beforeunload',event=>{if(dirtyBuffers().length){event.preventDefault();event.returnValue='';}});
  document.addEventListener('click',async event=>{const link=event.target.closest('a[href]');if(!link||!dirtyBuffers().length||event.ctrlKey||event.metaKey||link.target==='_blank')return;if(link.origin===location.origin){event.preventDefault();if(await dialog('Leave unsaved world edits?','<p>Save world to keep your pending terrain and event edits. Leaving now discards those unsaved edits.</p>','Discard and leave')){S.buffers.forEach(b=>b.dirty=false);location.href=link.href;}}});
  new ResizeObserver(resizeCanvas).observe(viewport);
  async function init(){try{const [session,catalog,areas,objects,allMaps]=await Promise.all([api('/api/session'),api('/api/worldmap'),api('/api/areas'),api('/api/world/objects'),api('/api/world/maps')]);S.token=session.token;S.catalog=catalog;S.maps=catalog.maps;S.byName=new Map(S.maps.map(row=>[row.name,row]));S.areas=areas.areas;S.areas.forEach(area=>area.maps.forEach(row=>S.areaByMap.set(row.name,area)));S.objects=objects.objects;S.objectById=new Map(S.objects.map(object=>[object.id,object]));$('#map-ids').replaceChildren(...allMaps.maps.map(row=>{const option=node('option');option.value=row.id;option.label=nice(row.name);return option;}));$('#object-ids').replaceChildren(...S.objects.map(object=>{const option=node('option');option.value=object.id;option.label=object.name;return option;}));resizeCanvas();fitBounds(catalog.bounds);const requested=new URLSearchParams(location.search).get('map'),first=S.byName.has(requested)?requested:S.byName.has('LittlerootTown')?'LittlerootTown':S.maps[0]?.name;if(first)await selectMap(first);if(S.byName.has(requested))fitSelection();S.ready=true;$$('[data-tool],[data-mode]').forEach(button=>button.disabled=false);['place-search','category-filter','fit-category','fit-world','zoom-out','zoom-in','zoom-value'].forEach(id=>$(`#${id}`).disabled=false);$('#loading').hidden=true;renderObjects();status();render();preload();}catch(err){$('#loading').hidden=true;error(err.message);$('#save-status').textContent='Could not load the world';}}
  window.WorldTools?.configure({
    getSelection:()=>S.selected,
    beforeOpen:async()=>{if(!S.ready||S.busy||S.finishing)return false;await finishStroke();return requireSavedWorld();},
    onClose:async(preferred,details={})=>{if(S.busy||S.finishing||dirtyBuffers().length)return false;if(details.sourceChanged){S.busy=true;status();try{await reloadWorld(preferred||S.selected,!!preferred);}catch(err){error(err.message);toast(err.message,true);return false;}finally{S.busy=false;status();}}else if(preferred&&map(preferred)){await selectMap(preferred);fitSelection();}return true;}
  });
  init();
})();
